/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[9] = {2.3200000000000000e-03, 0., 0., 0., 2.3200000000000000e-03, 0., 0., 0., 4.0000000000000001e-03};
static const casadi_real casadi_c2[9] = {4.3103448275862070e+02, 0., 0., 0., 4.3103448275862070e+02, 0., 0., 0., 250.};

/* drone_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, *w1=w+16, *w2=w+19, *w3=w+22, *w4=w+26, *w5=w+29, w6, w7, *w8=w+35, w9, w10, w11, w12, w13, w14, *w15=w+44, *w16=w+47, *w17=w+50, *w18=w+54, *w19=w+57, *w20=w+60, w21, w22, w23, w24, w25, w26, w27, *w28=w+70, w29, w30, w31, w32, w33, *w34=w+78, w35, *w36=w+83, *w37=w+92, *w38=w+101;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  casadi_copy(w0+10, 3, w4);
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @5 = zeros(4x1) */
  casadi_clear(w5, 4);
  /* #4: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #5: @6 = @1[1] */
  for (rr=(&w6), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #7: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #8: {@7, @8} = vertsplit(@3) */
  w7 = w3[0];
  casadi_copy(w3+1, 3, w8);
  /* #9: {@9, @10, @11} = vertsplit(@8) */
  w9 = w8[0];
  w10 = w8[1];
  w11 = w8[2];
  /* #10: @12 = (@6*@11) */
  w12  = (w6*w11);
  /* #11: @13 = @1[2] */
  for (rr=(&w13), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #12: @14 = (@13*@10) */
  w14  = (w13*w10);
  /* #13: @12 = (@12-@14) */
  w12 -= w14;
  /* #14: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #15: @12 = @1[0] */
  for (rr=(&w12), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #17: @6 = (@6*@9) */
  w6 *= w9;
  /* #18: @14 = (@14-@6) */
  w14 -= w6;
  /* #19: (@5[3] += @14) */
  for (rr=w5+3, ss=(&w14); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #20: @13 = (@13*@9) */
  w13 *= w9;
  /* #21: @12 = (@12*@11) */
  w12 *= w11;
  /* #22: @13 = (@13-@12) */
  w13 -= w12;
  /* #23: (@5[2] += @13) */
  for (rr=w5+2, ss=(&w13); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #24: @13 = dot(@1, @8) */
  w13 = casadi_dot(3, w1, w8);
  /* #25: (@5[0] += @13) */
  for (rr=w5+0, ss=(&w13); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #26: @15 = (@7*@1) */
  for (i=0, rr=w15, cs=w1; i<3; ++i) (*rr++)  = (w7*(*cs++));
  /* #27: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #28: (@5[1:4] += @15) */
  for (rr=w5+1, ss=w15; rr!=w5+4; rr+=1) *rr += *ss++;
  /* #29: @15 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w15);
  /* #30: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #31: @13 = @3[0] */
  for (rr=(&w13), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #32: @16 = @3[1:4] */
  for (rr=w16, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #33: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #34: @17 = vertcat(@13, @16) */
  rr=w17;
  *rr++ = w13;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #35: @13 = ||@3||_F */
  w13 = sqrt(casadi_dot(4, w3, w3));
  /* #36: @12 = sq(@13) */
  w12 = casadi_sq( w13 );
  /* #37: @17 = (@17/@12) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) /= w12;
  /* #38: @16 = @17[1:4] */
  for (rr=w16, ss=w17+1; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #39: @14 = input[2][0] */
  w14 = arg[2] ? arg[2][0] : 0;
  /* #40: @2 = (2.*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #41: @18 = (@14*@2) */
  for (i=0, rr=w18, cs=w2; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #42: @19 = (-@18) */
  for (i=0, rr=w19, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #43: @14 = dot(@16, @19) */
  w14 = casadi_dot(3, w16, w19);
  /* #44: @19 = (@15*@14) */
  for (i=0, rr=w19, cr=w15; i<3; ++i) (*rr++)  = ((*cr++)*w14);
  /* #45: (@5[1:4] += @19) */
  for (rr=w5+1, ss=w19; rr!=w5+4; rr+=1) *rr += *ss++;
  /* #46: @19 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w19);
  /* #47: @14 = @19[1] */
  for (rr=(&w14), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #48: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #49: @6 = @17[2] */
  for (rr=(&w6), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #50: {@21, @22, @23} = vertsplit(@18) */
  w21 = w18[0];
  w22 = w18[1];
  w23 = w18[2];
  /* #51: @24 = (@6*@23) */
  w24  = (w6*w23);
  /* #52: @25 = @17[3] */
  for (rr=(&w25), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #53: @26 = (@25*@22) */
  w26  = (w25*w22);
  /* #54: @24 = (@24-@26) */
  w24 -= w26;
  /* #55: (@20[0] += @24) */
  for (rr=w20+0, ss=(&w24); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #56: @24 = @17[1] */
  for (rr=(&w24), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #57: @26 = (@24*@22) */
  w26  = (w24*w22);
  /* #58: @27 = (@6*@21) */
  w27  = (w6*w21);
  /* #59: @26 = (@26-@27) */
  w26 -= w27;
  /* #60: (@20[2] += @26) */
  for (rr=w20+2, ss=(&w26); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #61: @26 = (@25*@21) */
  w26  = (w25*w21);
  /* #62: @27 = (@24*@23) */
  w27  = (w24*w23);
  /* #63: @26 = (@26-@27) */
  w26 -= w27;
  /* #64: (@20[1] += @26) */
  for (rr=w20+1, ss=(&w26); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #65: @26 = @17[0] */
  for (rr=(&w26), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #66: @28 = (@26*@18) */
  for (i=0, rr=w28, cs=w18; i<3; ++i) (*rr++)  = (w26*(*cs++));
  /* #67: @20 = (@20+@28) */
  for (i=0, rr=w20, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #68: {@27, @29, @30} = vertsplit(@20) */
  w27 = w20[0];
  w29 = w20[1];
  w30 = w20[2];
  /* #69: @31 = (@14*@30) */
  w31  = (w14*w30);
  /* #70: @32 = @19[2] */
  for (rr=(&w32), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #71: @33 = (@32*@29) */
  w33  = (w32*w29);
  /* #72: @31 = (@31-@33) */
  w31 -= w33;
  /* #73: (@5[1] += @31) */
  for (rr=w5+1, ss=(&w31); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #74: @31 = @19[0] */
  for (rr=(&w31), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #75: @29 = (@31*@29) */
  w29  = (w31*w29);
  /* #76: @33 = (@14*@27) */
  w33  = (w14*w27);
  /* #77: @29 = (@29-@33) */
  w29 -= w33;
  /* #78: (@5[3] += @29) */
  for (rr=w5+3, ss=(&w29); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #79: @27 = (@32*@27) */
  w27  = (w32*w27);
  /* #80: @30 = (@31*@30) */
  w30  = (w31*w30);
  /* #81: @27 = (@27-@30) */
  w27 -= w30;
  /* #82: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #83: @19 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w19);
  /* #84: @27 = dot(@19, @20) */
  w27 = casadi_dot(3, w19, w20);
  /* #85: (@5[0] += @27) */
  for (rr=w5+0, ss=(&w27); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #86: @27 = (2.*@13) */
  w27 = (2.* w13 );
  /* #87: @17 = (@17/@12) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) /= w12;
  /* #88: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<4; ++i) *rr++ = (- *cs++ );
  /* #89: @34 = zeros(4x1) */
  casadi_clear(w34, 4);
  /* #90: @30 = @3[0] */
  for (rr=(&w30), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #91: @19 = (@19*@30) */
  for (i=0, rr=w19; i<3; ++i) (*rr++) *= w30;
  /* #92: @30 = @3[2] */
  for (rr=(&w30), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #93: @29 = (@30*@32) */
  w29  = (w30*w32);
  /* #94: @33 = @3[3] */
  for (rr=(&w33), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #95: @35 = (@33*@14) */
  w35  = (w33*w14);
  /* #96: @29 = (@29-@35) */
  w29 -= w35;
  /* #97: @33 = (@33*@31) */
  w33 *= w31;
  /* #98: @35 = @3[1] */
  for (rr=(&w35), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #99: @32 = (@35*@32) */
  w32  = (w35*w32);
  /* #100: @33 = (@33-@32) */
  w33 -= w32;
  /* #101: @35 = (@35*@14) */
  w35 *= w14;
  /* #102: @30 = (@30*@31) */
  w30 *= w31;
  /* #103: @35 = (@35-@30) */
  w35 -= w30;
  /* #104: @20 = vertcat(@29, @33, @35) */
  rr=w20;
  *rr++ = w29;
  *rr++ = w33;
  *rr++ = w35;
  /* #105: @19 = (@19+@20) */
  for (i=0, rr=w19, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #106: @29 = @19[2] */
  for (rr=(&w29), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #107: @33 = (@29*@22) */
  w33  = (w29*w22);
  /* #108: @35 = @19[1] */
  for (rr=(&w35), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #109: @30 = (@35*@23) */
  w30  = (w35*w23);
  /* #110: @33 = (@33-@30) */
  w33 -= w30;
  /* #111: (@34[1] += @33) */
  for (rr=w34+1, ss=(&w33); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #112: @33 = @19[0] */
  for (rr=(&w33), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #113: @23 = (@33*@23) */
  w23  = (w33*w23);
  /* #114: @30 = (@29*@21) */
  w30  = (w29*w21);
  /* #115: @23 = (@23-@30) */
  w23 -= w30;
  /* #116: (@34[2] += @23) */
  for (rr=w34+2, ss=(&w23); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #117: @21 = (@35*@21) */
  w21  = (w35*w21);
  /* #118: @22 = (@33*@22) */
  w22  = (w33*w22);
  /* #119: @21 = (@21-@22) */
  w21 -= w22;
  /* #120: (@34[3] += @21) */
  for (rr=w34+3, ss=(&w21); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #121: @20 = @3[1:4] */
  for (rr=w20, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #122: @21 = dot(@20, @15) */
  w21 = casadi_dot(3, w20, w15);
  /* #123: @20 = (@21*@18) */
  for (i=0, rr=w20, cs=w18; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #124: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #125: (@34[1:4] += @20) */
  for (rr=w34+1, ss=w20; rr!=w34+4; rr+=1) *rr += *ss++;
  /* #126: @22 = dot(@19, @18) */
  w22 = casadi_dot(3, w19, w18);
  /* #127: (@34[0] += @22) */
  for (rr=w34+0, ss=(&w22); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #128: @22 = dot(@17, @34) */
  w22 = casadi_dot(4, w17, w34);
  /* #129: @27 = (@27*@22) */
  w27 *= w22;
  /* #130: @27 = (@27/@13) */
  w27 /= w13;
  /* #131: @17 = (@27*@3) */
  for (i=0, rr=w17, cs=w3; i<4; ++i) (*rr++)  = (w27*(*cs++));
  /* #132: @5 = (@5+@17) */
  for (i=0, rr=w5, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #133: @34 = (@34/@12) */
  for (i=0, rr=w34; i<4; ++i) (*rr++) /= w12;
  /* #134: {@12, @18} = vertsplit(@34) */
  w12 = w34[0];
  casadi_copy(w34+1, 3, w18);
  /* #135: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #136: (@5[1:4] += @18) */
  for (rr=w5+1, ss=w18; rr!=w5+4; rr+=1) *rr += *ss++;
  /* #137: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #138: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 4, res[0]+3);
  /* #139: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #140: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #141: @36 = 
  [[0.00232, 0, 0], 
   [0, 0.00232, 0], 
   [0, 0, 0.004]] */
  casadi_copy(casadi_c1, 9, w36);
  /* #142: @20 = mac(@36,@1,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w36+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #143: @12 = @20[1] */
  for (rr=(&w12), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #144: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #145: @37 = 
  [[431.034, 0, 0], 
   [0, 431.034, 0], 
   [0, 0, 250]] */
  casadi_copy(casadi_c2, 9, w37);
  /* #146: @38 = @37' */
  for (i=0, rr=w38, cs=w37; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #147: @15 = mac(@38,@4,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w38+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #148: @4 = (-@15) */
  for (i=0, rr=w4, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #149: {@27, @13, @22} = vertsplit(@4) */
  w27 = w4[0];
  w13 = w4[1];
  w22 = w4[2];
  /* #150: @23 = (@12*@22) */
  w23  = (w12*w22);
  /* #151: @30 = @20[2] */
  for (rr=(&w30), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #152: @31 = (@30*@13) */
  w31  = (w30*w13);
  /* #153: @23 = (@23-@31) */
  w23 -= w31;
  /* #154: (@18[0] += @23) */
  for (rr=w18+0, ss=(&w23); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #155: @23 = @20[0] */
  for (rr=(&w23), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #156: @31 = (@23*@13) */
  w31  = (w23*w13);
  /* #157: @12 = (@12*@27) */
  w12 *= w27;
  /* #158: @31 = (@31-@12) */
  w31 -= w12;
  /* #159: (@18[2] += @31) */
  for (rr=w18+2, ss=(&w31); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #160: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #161: @38 = @36' */
  for (i=0, rr=w38, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #162: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #163: @31 = @1[2] */
  for (rr=(&w31), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #164: @12 = (@31*@13) */
  w12  = (w31*w13);
  /* #165: @14 = @1[1] */
  for (rr=(&w14), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #166: @32 = (@14*@22) */
  w32  = (w14*w22);
  /* #167: @12 = (@12-@32) */
  w12 -= w32;
  /* #168: (@4[0] += @12) */
  for (rr=w4+0, ss=(&w12); rr!=w4+1; rr+=1) *rr += *ss++;
  /* #169: @12 = @1[0] */
  for (rr=(&w12), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #170: @32 = (@12*@22) */
  w32  = (w12*w22);
  /* #171: @31 = (@31*@27) */
  w31 *= w27;
  /* #172: @32 = (@32-@31) */
  w32 -= w31;
  /* #173: (@4[1] += @32) */
  for (rr=w4+1, ss=(&w32); rr!=w4+2; rr+=1) *rr += *ss++;
  /* #174: @14 = (@14*@27) */
  w14 *= w27;
  /* #175: @12 = (@12*@13) */
  w12 *= w13;
  /* #176: @14 = (@14-@12) */
  w14 -= w12;
  /* #177: (@4[2] += @14) */
  for (rr=w4+2, ss=(&w14); rr!=w4+3; rr+=1) *rr += *ss++;
  /* #178: @20 = mac(@38,@4,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w38+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #179: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #180: @30 = (@30*@27) */
  w30 *= w27;
  /* #181: @23 = (@23*@22) */
  w23 *= w22;
  /* #182: @30 = (@30-@23) */
  w30 -= w23;
  /* #183: (@18[1] += @30) */
  for (rr=w18+1, ss=(&w30); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #184: @30 = @3[3] */
  for (rr=(&w30), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #185: @23 = (@30*@10) */
  w23  = (w30*w10);
  /* #186: @22 = @3[2] */
  for (rr=(&w22), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #187: @27 = (@22*@11) */
  w27  = (w22*w11);
  /* #188: @23 = (@23-@27) */
  w23 -= w27;
  /* #189: (@18[0] += @23) */
  for (rr=w18+0, ss=(&w23); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #190: @23 = @3[1] */
  for (rr=(&w23), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #191: @11 = (@23*@11) */
  w11  = (w23*w11);
  /* #192: @30 = (@30*@9) */
  w30 *= w9;
  /* #193: @11 = (@11-@30) */
  w11 -= w30;
  /* #194: (@18[1] += @11) */
  for (rr=w18+1, ss=(&w11); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #195: @22 = (@22*@9) */
  w22 *= w9;
  /* #196: @23 = (@23*@10) */
  w23 *= w10;
  /* #197: @22 = (@22-@23) */
  w22 -= w23;
  /* #198: (@18[2] += @22) */
  for (rr=w18+2, ss=(&w22); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #199: @22 = @3[0] */
  for (rr=(&w22), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #200: @8 = (@22*@8) */
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w22*(*cs++));
  /* #201: @18 = (@18+@8) */
  for (i=0, rr=w18, cs=w8; i<3; ++i) (*rr++) += (*cs++);
  /* #202: @8 = @3[1:4] */
  for (rr=w8, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #203: @8 = (@7*@8) */
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w7*(*cs++));
  /* #204: @18 = (@18-@8) */
  for (i=0, rr=w18, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  /* #205: output[0][2] = @18 */
  if (res[0]) casadi_copy(w18, 3, res[0]+7);
  /* #206: @19 = (@26*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w26*(*cs++));
  /* #207: @16 = (@21*@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #208: @19 = (@19-@16) */
  for (i=0, rr=w19, cs=w16; i<3; ++i) (*rr++) -= (*cs++);
  /* #209: @21 = (@35*@25) */
  w21  = (w35*w25);
  /* #210: @26 = (@29*@6) */
  w26  = (w29*w6);
  /* #211: @21 = (@21-@26) */
  w21 -= w26;
  /* #212: @29 = (@29*@24) */
  w29 *= w24;
  /* #213: @25 = (@33*@25) */
  w25  = (w33*w25);
  /* #214: @29 = (@29-@25) */
  w29 -= w25;
  /* #215: @33 = (@33*@6) */
  w33 *= w6;
  /* #216: @35 = (@35*@24) */
  w35 *= w24;
  /* #217: @33 = (@33-@35) */
  w33 -= w35;
  /* #218: @16 = vertcat(@21, @29, @33) */
  rr=w16;
  *rr++ = w21;
  *rr++ = w29;
  *rr++ = w33;
  /* #219: @19 = (@19+@16) */
  for (i=0, rr=w19, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #220: @21 = dot(@19, @2) */
  w21 = casadi_dot(3, w19, w2);
  /* #221: output[0][3] = @21 */
  if (res[0]) res[0][10] = w21;
  /* #222: output[0][4] = @15 */
  if (res[0]) casadi_copy(w15, 3, res[0]+11);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 110;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
