/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 0., 9.8000000000000007e+00};
static const casadi_real casadi_c2[9] = {4.3103448275862070e+02, 0., 0., 0., 4.3103448275862070e+02, 0., 0., 0., 250.};
static const casadi_real casadi_c3[9] = {2.3200000000000000e-03, 0., 0., 0., 2.3200000000000000e-03, 0., 0., 0., 4.0000000000000001e-03};

/* drone_expl_ode_fun:(i0[13],i1[4],i2[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, *w2=w+7, w3, *w4=w+12, w5, *w6=w+17, w7, w8, w9, w10, w11, w12, *w13=w+26, *w14=w+29, *w15=w+32, *w16=w+41;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #3: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w2);
  /* #4: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #5: @0 = @2[1:4] */
  for (rr=w0, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #6: @0 = (-@0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) *rr++ = (- *cs++ );
  /* #7: @4 = vertcat(@3, @0) */
  rr=w4;
  *rr++ = w3;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  /* #8: @3 = ||@2||_F */
  w3 = sqrt(casadi_dot(4, w2, w2));
  /* #9: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #10: @4 = (@4/@3) */
  for (i=0, rr=w4; i<4; ++i) (*rr++) /= w3;
  /* #11: @3 = @4[0] */
  for (rr=(&w3), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #12: @0 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w0);
  /* #13: @5 = @2[0] */
  for (rr=(&w5), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #14: @0 = (@0*@5) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) *= w5;
  /* #15: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #16: @6 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w6);
  /* #17: @7 = @6[2] */
  for (rr=(&w7), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #18: @8 = (@5*@7) */
  w8  = (w5*w7);
  /* #19: @9 = @2[3] */
  for (rr=(&w9), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #20: @10 = @6[1] */
  for (rr=(&w10), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@9*@10) */
  w11  = (w9*w10);
  /* #22: @8 = (@8-@11) */
  w8 -= w11;
  /* #23: @11 = @6[0] */
  for (rr=(&w11), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #24: @9 = (@9*@11) */
  w9 *= w11;
  /* #25: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #26: @7 = (@12*@7) */
  w7  = (w12*w7);
  /* #27: @9 = (@9-@7) */
  w9 -= w7;
  /* #28: @12 = (@12*@10) */
  w12 *= w10;
  /* #29: @5 = (@5*@11) */
  w5 *= w11;
  /* #30: @12 = (@12-@5) */
  w12 -= w5;
  /* #31: @6 = vertcat(@8, @9, @12) */
  rr=w6;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w12;
  /* #32: @0 = (@0+@6) */
  for (i=0, rr=w0, cs=w6; i<3; ++i) (*rr++) += (*cs++);
  /* #33: @6 = (@3*@0) */
  for (i=0, rr=w6, cs=w0; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #34: @13 = @2[1:4] */
  for (rr=w13, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #35: @14 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w14);
  /* #36: @3 = dot(@13, @14) */
  w3 = casadi_dot(3, w13, w14);
  /* #37: @13 = @4[1:4] */
  for (rr=w13, ss=w4+1; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #38: @13 = (@3*@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #39: @6 = (@6-@13) */
  for (i=0, rr=w6, cs=w13; i<3; ++i) (*rr++) -= (*cs++);
  /* #40: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #41: @8 = @4[3] */
  for (rr=(&w8), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #42: @9 = (@3*@8) */
  w9  = (w3*w8);
  /* #43: @12 = @0[2] */
  for (rr=(&w12), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #44: @5 = @4[2] */
  for (rr=(&w5), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #45: @11 = (@12*@5) */
  w11  = (w12*w5);
  /* #46: @9 = (@9-@11) */
  w9 -= w11;
  /* #47: @11 = @4[1] */
  for (rr=(&w11), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #48: @12 = (@12*@11) */
  w12 *= w11;
  /* #49: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #50: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #51: @12 = (@12-@8) */
  w12 -= w8;
  /* #52: @10 = (@10*@5) */
  w10 *= w5;
  /* #53: @3 = (@3*@11) */
  w3 *= w11;
  /* #54: @10 = (@10-@3) */
  w10 -= w3;
  /* #55: @0 = vertcat(@9, @12, @10) */
  rr=w0;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w10;
  /* #56: @6 = (@6+@0) */
  for (i=0, rr=w6, cs=w0; i<3; ++i) (*rr++) += (*cs++);
  /* #57: @6 = (@1*@6) */
  for (i=0, rr=w6, cs=w6; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #58: @6 = (2.*@6) */
  for (i=0, rr=w6, cs=w6; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #59: @0 = [0, 0, 9.8] */
  casadi_copy(casadi_c1, 3, w0);
  /* #60: @6 = (@6-@0) */
  for (i=0, rr=w6, cs=w0; i<3; ++i) (*rr++) -= (*cs++);
  /* #61: output[0][1] = @6 */
  if (res[0]) casadi_copy(w6, 3, res[0]+3);
  /* #62: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #63: @6 = @2[1:4] */
  for (rr=w6, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #64: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #65: @9 = dot(@6, @0) */
  w9 = casadi_dot(3, w6, w0);
  /* #66: @9 = (-@9) */
  w9 = (- w9 );
  /* #67: @12 = @2[0] */
  for (rr=(&w12), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #68: @6 = (@12*@0) */
  for (i=0, rr=w6, cs=w0; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #69: @12 = @2[2] */
  for (rr=(&w12), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #70: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #71: @3 = (@12*@10) */
  w3  = (w12*w10);
  /* #72: @11 = @2[3] */
  for (rr=(&w11), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #73: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #74: @8 = (@11*@5) */
  w8  = (w11*w5);
  /* #75: @3 = (@3-@8) */
  w3 -= w8;
  /* #76: @8 = @0[0] */
  for (rr=(&w8), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #77: @11 = (@11*@8) */
  w11 *= w8;
  /* #78: @7 = @2[1] */
  for (rr=(&w7), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #79: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #80: @11 = (@11-@10) */
  w11 -= w10;
  /* #81: @7 = (@7*@5) */
  w7 *= w5;
  /* #82: @12 = (@12*@8) */
  w12 *= w8;
  /* #83: @7 = (@7-@12) */
  w7 -= w12;
  /* #84: @13 = vertcat(@3, @11, @7) */
  rr=w13;
  *rr++ = w3;
  *rr++ = w11;
  *rr++ = w7;
  /* #85: @6 = (@6+@13) */
  for (i=0, rr=w6, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #86: @2 = vertcat(@9, @6) */
  rr=w2;
  *rr++ = w9;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  /* #87: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #88: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 4, res[0]+6);
  /* #89: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #90: @15 = 
  [[431.034, 0, 0], 
   [0, 431.034, 0], 
   [0, 0, 250]] */
  casadi_copy(casadi_c2, 9, w15);
  /* #91: @13 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w13);
  /* #92: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #93: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #94: @16 = 
  [[0.00232, 0, 0], 
   [0, 0.00232, 0], 
   [0, 0, 0.004]] */
  casadi_copy(casadi_c3, 9, w16);
  /* #95: @14 = mac(@16,@0,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #96: @9 = @14[2] */
  for (rr=(&w9), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #97: @3 = (@1*@9) */
  w3  = (w1*w9);
  /* #98: @11 = @0[2] */
  for (rr=(&w11), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #99: @7 = @14[1] */
  for (rr=(&w7), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #100: @12 = (@11*@7) */
  w12  = (w11*w7);
  /* #101: @3 = (@3-@12) */
  w3 -= w12;
  /* #102: @12 = @14[0] */
  for (rr=(&w12), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #103: @11 = (@11*@12) */
  w11 *= w12;
  /* #104: @8 = @0[0] */
  for (rr=(&w8), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #105: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #106: @11 = (@11-@9) */
  w11 -= w9;
  /* #107: @8 = (@8*@7) */
  w8 *= w7;
  /* #108: @1 = (@1*@12) */
  w1 *= w12;
  /* #109: @8 = (@8-@1) */
  w8 -= w1;
  /* #110: @0 = vertcat(@3, @11, @8) */
  rr=w0;
  *rr++ = w3;
  *rr++ = w11;
  *rr++ = w8;
  /* #111: @13 = (@13-@0) */
  for (i=0, rr=w13, cs=w0; i<3; ++i) (*rr++) -= (*cs++);
  /* #112: @6 = mac(@15,@13,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #113: output[0][3] = @6 */
  if (res[0]) casadi_copy(w6, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 50;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
