/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[13] = {21, 2, 0, 4, 8, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s5[3] = {2, 0, 0};

/* drone_simple_drag_constr_h_fun_jac_uxt_zt:(i0[17],i1[4],i2[],i3[])->(o0[2],o1[21x2,8nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+18, *w16=w+26, *w17=w+44;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[1] */
  for (rr=(&w2), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #4: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #5: @5 = @0[3] */
  for (rr=(&w5), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #6: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #7: @3 = (@3+@6) */
  w3 += w6;
  /* #8: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #9: @6 = 1 */
  w6 = 1.;
  /* #10: @7 = @0[1] */
  for (rr=(&w7), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #11: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #12: @9 = @0[2] */
  for (rr=(&w9), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #13: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #14: @8 = (@8+@10) */
  w8 += w10;
  /* #15: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #16: @6 = (@6-@8) */
  w6 -= w8;
  /* #17: @3 = (@3/@6) */
  w3 /= w6;
  /* #18: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #19: @8 = @0[0] */
  for (rr=(&w8), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #20: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@8*@10) */
  w11  = (w8*w10);
  /* #22: @12 = @0[1] */
  for (rr=(&w12), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #23: @13 = @0[3] */
  for (rr=(&w13), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #24: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #25: @11 = (@11-@14) */
  w11 -= w14;
  /* #26: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #27: output[0][1] = @11 */
  if (res[0]) res[0][1] = w11;
  /* #28: @15 = zeros(21x2,8nz) */
  casadi_clear(w15, 8);
  /* #29: @16 = ones(21x1,18nz) */
  casadi_fill(w16, 18, 1.);
  /* #30: {NULL, NULL, NULL, NULL, @11, NULL, NULL, NULL} = vertsplit(@16) */
  w11 = w16[10];
  /* #31: @14 = @11[0] */
  for (rr=(&w14), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #32: @2 = (@2*@14) */
  w2 *= w14;
  /* #33: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #34: @2 = (@2/@6) */
  w2 /= w6;
  /* #35: @14 = @11[0] */
  for (rr=(&w14), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #36: @10 = (@10*@14) */
  w10 *= w14;
  /* #37: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #38: @17 = vertcat(@2, @10) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w10;
  /* #39: (@15[:8:4] = @17) */
  for (rr=w15+0, ss=w17; rr!=w15+8; rr+=4) *rr = *ss++;
  /* #40: @2 = ones(21x1,1nz) */
  w2 = 1.;
  /* #41: {NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL} = vertsplit(@2) */
  w10 = w2;
  /* #42: @2 = @10[0] */
  for (rr=(&w2), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #43: @1 = (@1*@2) */
  w1 *= w2;
  /* #44: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #45: @1 = (@1/@6) */
  w1 /= w6;
  /* #46: @3 = (@3/@6) */
  w3 /= w6;
  /* #47: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #48: @2 = @10[0] */
  for (rr=(&w2), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #49: @7 = (@7*@2) */
  w7 *= w2;
  /* #50: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #51: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #52: @1 = (@1+@7) */
  w1 += w7;
  /* #53: @7 = @10[0] */
  for (rr=(&w7), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #54: @13 = (@13*@7) */
  w13 *= w7;
  /* #55: @13 = (-@13) */
  w13 = (- w13 );
  /* #56: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #57: @17 = vertcat(@1, @13) */
  rr=w17;
  *rr++ = w1;
  *rr++ = w13;
  /* #58: (@15[1:9:4] = @17) */
  for (rr=w15+1, ss=w17; rr!=w15+9; rr+=4) *rr = *ss++;
  /* #59: @1 = ones(21x1,1nz) */
  w1 = 1.;
  /* #60: {NULL, NULL, NULL, NULL, @13, NULL, NULL, NULL} = vertsplit(@1) */
  w13 = w1;
  /* #61: @1 = @13[0] */
  for (rr=(&w1), ss=(&w13)+0; ss!=(&w13)+1; ss+=1) *rr++ = *ss;
  /* #62: @5 = (@5*@1) */
  w5 *= w1;
  /* #63: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #64: @5 = (@5/@6) */
  w5 /= w6;
  /* #65: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #66: @1 = @13[0] */
  for (rr=(&w1), ss=(&w13)+0; ss!=(&w13)+1; ss+=1) *rr++ = *ss;
  /* #67: @9 = (@9*@1) */
  w9 *= w1;
  /* #68: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #69: @3 = (@3*@9) */
  w3 *= w9;
  /* #70: @5 = (@5+@3) */
  w5 += w3;
  /* #71: @3 = @13[0] */
  for (rr=(&w3), ss=(&w13)+0; ss!=(&w13)+1; ss+=1) *rr++ = *ss;
  /* #72: @8 = (@8*@3) */
  w8 *= w3;
  /* #73: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #74: @17 = vertcat(@5, @8) */
  rr=w17;
  *rr++ = w5;
  *rr++ = w8;
  /* #75: (@15[2:10:4] = @17) */
  for (rr=w15+2, ss=w17; rr!=w15+10; rr+=4) *rr = *ss++;
  /* #76: @5 = ones(21x1,1nz) */
  w5 = 1.;
  /* #77: {NULL, NULL, NULL, NULL, @8, NULL, NULL, NULL} = vertsplit(@5) */
  w8 = w5;
  /* #78: @5 = @8[0] */
  for (rr=(&w5), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #79: @4 = (@4*@5) */
  w4 *= w5;
  /* #80: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #81: @4 = (@4/@6) */
  w4 /= w6;
  /* #82: @6 = @8[0] */
  for (rr=(&w6), ss=(&w8)+0; ss!=(&w8)+1; ss+=1) *rr++ = *ss;
  /* #83: @12 = (@12*@6) */
  w12 *= w6;
  /* #84: @12 = (-@12) */
  w12 = (- w12 );
  /* #85: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #86: @17 = vertcat(@4, @12) */
  rr=w17;
  *rr++ = w4;
  *rr++ = w12;
  /* #87: (@15[3:11:4] = @17) */
  for (rr=w15+3, ss=w17; rr!=w15+11; rr+=4) *rr = *ss++;
  /* #88: output[1][0] = @15 */
  casadi_copy(w15, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 46;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
