/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[8] = {10, 1, 0, 4, 6, 7, 8, 9};
static const casadi_int casadi_s4[3] = {1, 0, 0};

/* drone_simple_drag_constr_h_e_fun_jac_uxt_zt:(i0[10],i1[],i2[],i3[])->(o0,o1[10x1,4nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, *w11=w+14;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[3] */
  for (rr=(&w2), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #3: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #4: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #5: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #6: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #7: @3 = (@3+@6) */
  w3 += w6;
  /* #8: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #9: @6 = 1 */
  w6 = 1.;
  /* #10: @7 = @0[2] */
  for (rr=(&w7), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #11: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #12: @9 = @0[3] */
  for (rr=(&w9), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #13: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #14: @8 = (@8+@10) */
  w8 += w10;
  /* #15: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #16: @6 = (@6-@8) */
  w6 -= w8;
  /* #17: @3 = (@3/@6) */
  w3 /= w6;
  /* #18: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #19: @0 = zeros(10x1,4nz) */
  casadi_clear(w0, 4);
  /* #20: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #21: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #22: @3 = (@3/@6) */
  w3 /= w6;
  /* #23: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #24: @9 = (@9*@3) */
  w9 *= w3;
  /* #25: (@11[3] += @9) */
  for (rr=w11+3, ss=(&w9); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #26: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #27: @7 = (@7*@3) */
  w7 *= w3;
  /* #28: (@11[2] += @7) */
  for (rr=w11+2, ss=(&w7); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #29: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #30: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #31: @4 = (@4*@6) */
  w4 *= w6;
  /* #32: (@11[2] += @4) */
  for (rr=w11+2, ss=(&w4); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #33: @5 = (@5*@6) */
  w5 *= w6;
  /* #34: (@11[1] += @5) */
  for (rr=w11+1, ss=(&w5); rr!=w11+2; rr+=1) *rr += *ss++;
  /* #35: @1 = (@1*@6) */
  w1 *= w6;
  /* #36: (@11[3] += @1) */
  for (rr=w11+3, ss=(&w1); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #37: @2 = (@2*@6) */
  w2 *= w6;
  /* #38: (@11[0] += @2) */
  for (rr=w11+0, ss=(&w2); rr!=w11+1; rr+=1) *rr += *ss++;
  /* #39: @2 = @11[0] */
  for (rr=(&w2), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #40: (@0[0] = @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #41: @2 = @11[1] */
  for (rr=(&w2), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #42: (@0[1] = @2) */
  for (rr=w0+1, ss=(&w2); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #43: @2 = @11[2] */
  for (rr=(&w2), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #44: (@0[2] = @2) */
  for (rr=w0+2, ss=(&w2); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #45: @2 = @11[3] */
  for (rr=(&w2), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #46: (@0[3] = @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #47: output[1][0] = @0 */
  casadi_copy(w0, 4, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 18;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
