/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {-2.6000000000000001e-01, -2.8000000000000003e-01, -4.1999999999999998e-01};
static const casadi_real casadi_c2[3] = {0., 0., 9.8000000000000007e+00};

/* drone_simple_expl_ode_fun:(i0[10],i1[4],i2[])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+3, w2, *w3=w+8, *w4=w+11, w5, w6, *w7=w+17, w8, w9, w10, w11, w12, *w13=w+25, *w14=w+28, *w15=w+31, *w16=w+35, w17, w18, *w19=w+41;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w1);
  /* #3: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #4: @3 = @1[1:4] */
  for (rr=w3, ss=w1+1; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #5: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  /* #6: @4 = vertcat(@2, @3) */
  rr=w4;
  *rr++ = w2;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  /* #7: @2 = ||@1||_F */
  w2 = sqrt(casadi_dot(4, w1, w1));
  /* #8: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #9: @4 = (@4/@2) */
  for (i=0, rr=w4; i<4; ++i) (*rr++) /= w2;
  /* #10: @2 = @4[0] */
  for (rr=(&w2), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #11: @5 = @1[0] */
  for (rr=(&w5), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #12: @3 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w3);
  /* #13: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #14: @3 = (@3*@6) */
  for (i=0, rr=w3; i<3; ++i) (*rr++) *= w6;
  /* #15: @7 = (@5*@3) */
  for (i=0, rr=w7, cs=w3; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #16: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #17: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #18: @8 = (@5*@6) */
  w8  = (w5*w6);
  /* #19: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #20: @10 = @3[1] */
  for (rr=(&w10), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@9*@10) */
  w11  = (w9*w10);
  /* #22: @8 = (@8-@11) */
  w8 -= w11;
  /* #23: @11 = @3[0] */
  for (rr=(&w11), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #24: @9 = (@9*@11) */
  w9 *= w11;
  /* #25: @12 = @1[1] */
  for (rr=(&w12), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #26: @6 = (@12*@6) */
  w6  = (w12*w6);
  /* #27: @9 = (@9-@6) */
  w9 -= w6;
  /* #28: @12 = (@12*@10) */
  w12 *= w10;
  /* #29: @5 = (@5*@11) */
  w5 *= w11;
  /* #30: @12 = (@12-@5) */
  w12 -= w5;
  /* #31: @13 = vertcat(@8, @9, @12) */
  rr=w13;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w12;
  /* #32: @7 = (@7+@13) */
  for (i=0, rr=w7, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #33: @13 = (@2*@7) */
  for (i=0, rr=w13, cs=w7; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #34: @14 = @1[1:4] */
  for (rr=w14, ss=w1+1; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #35: @2 = dot(@14, @3) */
  w2 = casadi_dot(3, w14, w3);
  /* #36: @14 = @4[1:4] */
  for (rr=w14, ss=w4+1; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #37: @14 = (@2*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #38: @13 = (@13-@14) */
  for (i=0, rr=w13, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #39: @2 = @7[1] */
  for (rr=(&w2), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #40: @8 = @4[3] */
  for (rr=(&w8), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #41: @9 = (@2*@8) */
  w9  = (w2*w8);
  /* #42: @12 = @7[2] */
  for (rr=(&w12), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #43: @5 = @4[2] */
  for (rr=(&w5), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #44: @11 = (@12*@5) */
  w11  = (w12*w5);
  /* #45: @9 = (@9-@11) */
  w9 -= w11;
  /* #46: @11 = @4[1] */
  for (rr=(&w11), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #47: @12 = (@12*@11) */
  w12 *= w11;
  /* #48: @10 = @7[0] */
  for (rr=(&w10), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #49: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #50: @12 = (@12-@8) */
  w12 -= w8;
  /* #51: @10 = (@10*@5) */
  w10 *= w5;
  /* #52: @2 = (@2*@11) */
  w2 *= w11;
  /* #53: @10 = (@10-@2) */
  w10 -= w2;
  /* #54: @7 = vertcat(@9, @12, @10) */
  rr=w7;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w10;
  /* #55: @13 = (@13+@7) */
  for (i=0, rr=w13, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #56: @9 = @1[0] */
  for (rr=(&w9), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #57: @7 = @1[1:4] */
  for (rr=w7, ss=w1+1; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #58: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) *rr++ = (- *cs++ );
  /* #59: @4 = vertcat(@9, @7) */
  rr=w4;
  *rr++ = w9;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  /* #60: @9 = ||@1||_F */
  w9 = sqrt(casadi_dot(4, w1, w1));
  /* #61: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #62: @4 = (@4/@9) */
  for (i=0, rr=w4; i<4; ++i) (*rr++) /= w9;
  /* #63: @9 = @4[0] */
  for (rr=(&w9), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #64: @12 = @1[0] */
  for (rr=(&w12), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #65: @7 = [-0.26, -0.28, -0.42] */
  casadi_copy(casadi_c1, 3, w7);
  /* #66: @10 = @1[0] */
  for (rr=(&w10), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #67: @14 = @1[1:4] */
  for (rr=w14, ss=w1+1; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #68: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) *rr++ = (- *cs++ );
  /* #69: @15 = vertcat(@10, @14) */
  rr=w15;
  *rr++ = w10;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #70: @10 = ||@1||_F */
  w10 = sqrt(casadi_dot(4, w1, w1));
  /* #71: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #72: @15 = (@15/@10) */
  for (i=0, rr=w15; i<4; ++i) (*rr++) /= w10;
  /* #73: @10 = @15[0] */
  for (rr=(&w10), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #74: @14 = @15[1:4] */
  for (rr=w14, ss=w15+1; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #75: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) *rr++ = (- *cs++ );
  /* #76: @16 = vertcat(@10, @14) */
  rr=w16;
  *rr++ = w10;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #77: @10 = ||@15||_F */
  w10 = sqrt(casadi_dot(4, w15, w15));
  /* #78: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #79: @16 = (@16/@10) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w10;
  /* #80: @10 = @16[0] */
  for (rr=(&w10), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #81: @2 = @15[0] */
  for (rr=(&w2), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #82: @14 = (@2*@0) */
  for (i=0, rr=w14, cs=w0; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #83: @2 = @15[2] */
  for (rr=(&w2), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #84: @11 = @0[2] */
  for (rr=(&w11), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #85: @5 = (@2*@11) */
  w5  = (w2*w11);
  /* #86: @8 = @15[3] */
  for (rr=(&w8), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #87: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #88: @17 = (@8*@6) */
  w17  = (w8*w6);
  /* #89: @5 = (@5-@17) */
  w5 -= w17;
  /* #90: @17 = @0[0] */
  for (rr=(&w17), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #91: @8 = (@8*@17) */
  w8 *= w17;
  /* #92: @18 = @15[1] */
  for (rr=(&w18), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #93: @11 = (@18*@11) */
  w11  = (w18*w11);
  /* #94: @8 = (@8-@11) */
  w8 -= w11;
  /* #95: @18 = (@18*@6) */
  w18 *= w6;
  /* #96: @2 = (@2*@17) */
  w2 *= w17;
  /* #97: @18 = (@18-@2) */
  w18 -= w2;
  /* #98: @3 = vertcat(@5, @8, @18) */
  rr=w3;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w18;
  /* #99: @14 = (@14+@3) */
  for (i=0, rr=w14, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  /* #100: @3 = (@10*@14) */
  for (i=0, rr=w3, cs=w14; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #101: @19 = @15[1:4] */
  for (rr=w19, ss=w15+1; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #102: @10 = dot(@19, @0) */
  w10 = casadi_dot(3, w19, w0);
  /* #103: @19 = @16[1:4] */
  for (rr=w19, ss=w16+1; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #104: @19 = (@10*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #105: @3 = (@3-@19) */
  for (i=0, rr=w3, cs=w19; i<3; ++i) (*rr++) -= (*cs++);
  /* #106: @10 = @14[1] */
  for (rr=(&w10), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #107: @5 = @16[3] */
  for (rr=(&w5), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #108: @8 = (@10*@5) */
  w8  = (w10*w5);
  /* #109: @18 = @14[2] */
  for (rr=(&w18), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #110: @2 = @16[2] */
  for (rr=(&w2), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #111: @17 = (@18*@2) */
  w17  = (w18*w2);
  /* #112: @8 = (@8-@17) */
  w8 -= w17;
  /* #113: @17 = @16[1] */
  for (rr=(&w17), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #114: @18 = (@18*@17) */
  w18 *= w17;
  /* #115: @6 = @14[0] */
  for (rr=(&w6), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #116: @5 = (@6*@5) */
  w5  = (w6*w5);
  /* #117: @18 = (@18-@5) */
  w18 -= w5;
  /* #118: @6 = (@6*@2) */
  w6 *= w2;
  /* #119: @10 = (@10*@17) */
  w10 *= w17;
  /* #120: @6 = (@6-@10) */
  w6 -= w10;
  /* #121: @14 = vertcat(@8, @18, @6) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w18;
  *rr++ = w6;
  /* #122: @3 = (@3+@14) */
  for (i=0, rr=w3, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #123: @7 = (@7*@3) */
  for (i=0, rr=w7, cs=w3; i<3; ++i) (*rr++) *= (*cs++);
  /* #124: @14 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w14);
  /* #125: @8 = 0.01 */
  w8 = 1.0000000000000000e-02;
  /* #126: @18 = @3[0] */
  for (rr=(&w18), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #127: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #128: @6 = @3[1] */
  for (rr=(&w6), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #129: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #130: @18 = (@18+@6) */
  w18 += w6;
  /* #131: @8 = (@8*@18) */
  w8 *= w18;
  /* #132: @14 = (@14*@8) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) *= w8;
  /* #133: @7 = (@7+@14) */
  for (i=0, rr=w7, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #134: @14 = (@12*@7) */
  for (i=0, rr=w14, cs=w7; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #135: @12 = @1[2] */
  for (rr=(&w12), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #136: @8 = @7[2] */
  for (rr=(&w8), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #137: @18 = (@12*@8) */
  w18  = (w12*w8);
  /* #138: @6 = @1[3] */
  for (rr=(&w6), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #139: @10 = @7[1] */
  for (rr=(&w10), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #140: @17 = (@6*@10) */
  w17  = (w6*w10);
  /* #141: @18 = (@18-@17) */
  w18 -= w17;
  /* #142: @17 = @7[0] */
  for (rr=(&w17), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #143: @6 = (@6*@17) */
  w6 *= w17;
  /* #144: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #145: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #146: @6 = (@6-@8) */
  w6 -= w8;
  /* #147: @2 = (@2*@10) */
  w2 *= w10;
  /* #148: @12 = (@12*@17) */
  w12 *= w17;
  /* #149: @2 = (@2-@12) */
  w2 -= w12;
  /* #150: @3 = vertcat(@18, @6, @2) */
  rr=w3;
  *rr++ = w18;
  *rr++ = w6;
  *rr++ = w2;
  /* #151: @14 = (@14+@3) */
  for (i=0, rr=w14, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  /* #152: @3 = (@9*@14) */
  for (i=0, rr=w3, cs=w14; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #153: @19 = @1[1:4] */
  for (rr=w19, ss=w1+1; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #154: @9 = dot(@19, @7) */
  w9 = casadi_dot(3, w19, w7);
  /* #155: @19 = @4[1:4] */
  for (rr=w19, ss=w4+1; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #156: @19 = (@9*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #157: @3 = (@3-@19) */
  for (i=0, rr=w3, cs=w19; i<3; ++i) (*rr++) -= (*cs++);
  /* #158: @9 = @14[1] */
  for (rr=(&w9), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #159: @18 = @4[3] */
  for (rr=(&w18), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #160: @6 = (@9*@18) */
  w6  = (w9*w18);
  /* #161: @2 = @14[2] */
  for (rr=(&w2), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #162: @12 = @4[2] */
  for (rr=(&w12), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #163: @17 = (@2*@12) */
  w17  = (w2*w12);
  /* #164: @6 = (@6-@17) */
  w6 -= w17;
  /* #165: @17 = @4[1] */
  for (rr=(&w17), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #166: @2 = (@2*@17) */
  w2 *= w17;
  /* #167: @10 = @14[0] */
  for (rr=(&w10), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #168: @18 = (@10*@18) */
  w18  = (w10*w18);
  /* #169: @2 = (@2-@18) */
  w2 -= w18;
  /* #170: @10 = (@10*@12) */
  w10 *= w12;
  /* #171: @9 = (@9*@17) */
  w9 *= w17;
  /* #172: @10 = (@10-@9) */
  w10 -= w9;
  /* #173: @14 = vertcat(@6, @2, @10) */
  rr=w14;
  *rr++ = w6;
  *rr++ = w2;
  *rr++ = w10;
  /* #174: @3 = (@3+@14) */
  for (i=0, rr=w3, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #175: @13 = (@13+@3) */
  for (i=0, rr=w13, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  /* #176: @6 = 0.75 */
  w6 = 7.5000000000000000e-01;
  /* #177: @13 = (@13/@6) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) /= w6;
  /* #178: @3 = [0, 0, 9.8] */
  casadi_copy(casadi_c2, 3, w3);
  /* #179: @13 = (@13-@3) */
  for (i=0, rr=w13, cs=w3; i<3; ++i) (*rr++) -= (*cs++);
  /* #180: output[0][1] = @13 */
  if (res[0]) casadi_copy(w13, 3, res[0]+3);
  /* #181: @6 = 0.5 */
  w6 = 5.0000000000000000e-01;
  /* #182: @13 = @1[1:4] */
  for (rr=w13, ss=w1+1; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #183: @3 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w3);
  /* #184: @2 = dot(@13, @3) */
  w2 = casadi_dot(3, w13, w3);
  /* #185: @2 = (-@2) */
  w2 = (- w2 );
  /* #186: @10 = @1[0] */
  for (rr=(&w10), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #187: @13 = (@10*@3) */
  for (i=0, rr=w13, cs=w3; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #188: @10 = @1[2] */
  for (rr=(&w10), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #189: @9 = @3[2] */
  for (rr=(&w9), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #190: @17 = (@10*@9) */
  w17  = (w10*w9);
  /* #191: @12 = @1[3] */
  for (rr=(&w12), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #192: @18 = @3[1] */
  for (rr=(&w18), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #193: @8 = (@12*@18) */
  w8  = (w12*w18);
  /* #194: @17 = (@17-@8) */
  w17 -= w8;
  /* #195: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #196: @12 = (@12*@8) */
  w12 *= w8;
  /* #197: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #198: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #199: @12 = (@12-@9) */
  w12 -= w9;
  /* #200: @5 = (@5*@18) */
  w5 *= w18;
  /* #201: @10 = (@10*@8) */
  w10 *= w8;
  /* #202: @5 = (@5-@10) */
  w5 -= w10;
  /* #203: @3 = vertcat(@17, @12, @5) */
  rr=w3;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w5;
  /* #204: @13 = (@13+@3) */
  for (i=0, rr=w13, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  /* #205: @1 = vertcat(@2, @13) */
  rr=w1;
  *rr++ = w2;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #206: @1 = (@6*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #207: output[0][2] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+6);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 44;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
