/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {14, 1, 0, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

static const casadi_real casadi_c0[3] = {0., 0., 1.};

/* drone_simple_drag_expl_vde_adj:(i0[10],i1[10],i2[4],i3[])->(o0[14x1,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, w1, *w2=w+5, *w3=w+8, w4, w5, w6, *w7=w+15, *w8=w+18, w9, w10, w11, w12, w13, w14, w15, *w16=w+28, *w17=w+31, *w18=w+34, w19, w20, w21, w22, w23, w24, w25, *w26=w+44, *w27=w+54, *w28=w+57, *w29=w+61, *w30=w+64, *w31=w+67, w32, w33, w34, w35, w36, w37, *w38=w+77;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[1:4] */
  for (rr=w2, ss=w0+1; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #4: @3 = vertcat(@1, @2) */
  rr=w3;
  *rr++ = w1;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #5: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(4, w0, w0));
  /* #6: @4 = sq(@1) */
  w4 = casadi_sq( w1 );
  /* #7: @3 = (@3/@4) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) /= w4;
  /* #8: @5 = @3[0] */
  for (rr=(&w5), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #9: @2 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w2);
  /* #10: @6 = @0[0] */
  for (rr=(&w6), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@2*@6) */
  for (i=0, rr=w7, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)*w6);
  /* #12: @6 = @0[2] */
  for (rr=(&w6), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #13: @8 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w8);
  /* #14: @9 = @8[2] */
  for (rr=(&w9), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #15: @10 = (@6*@9) */
  w10  = (w6*w9);
  /* #16: @11 = @0[3] */
  for (rr=(&w11), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #17: @12 = @8[1] */
  for (rr=(&w12), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #18: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #19: @10 = (@10-@13) */
  w10 -= w13;
  /* #20: @13 = @8[0] */
  for (rr=(&w13), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@11*@13) */
  w11 *= w13;
  /* #22: @14 = @0[1] */
  for (rr=(&w14), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #23: @15 = (@14*@9) */
  w15  = (w14*w9);
  /* #24: @11 = (@11-@15) */
  w11 -= w15;
  /* #25: @14 = (@14*@12) */
  w14 *= w12;
  /* #26: @6 = (@6*@13) */
  w6 *= w13;
  /* #27: @14 = (@14-@6) */
  w14 -= w6;
  /* #28: @8 = vertcat(@10, @11, @14) */
  rr=w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w14;
  /* #29: @7 = (@7+@8) */
  for (i=0, rr=w7, cs=w8; i<3; ++i) (*rr++) += (*cs++);
  /* #30: @8 = (@5*@7) */
  for (i=0, rr=w8, cs=w7; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #31: @16 = @0[1:4] */
  for (rr=w16, ss=w0+1; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #32: @17 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w17);
  /* #33: @10 = dot(@16, @17) */
  w10 = casadi_dot(3, w16, w17);
  /* #34: @16 = @3[1:4] */
  for (rr=w16, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #35: @18 = (@10*@16) */
  for (i=0, rr=w18, cs=w16; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #36: @8 = (@8-@18) */
  for (i=0, rr=w8, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @11 = @7[1] */
  for (rr=(&w11), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #38: @14 = @3[3] */
  for (rr=(&w14), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #39: @6 = (@11*@14) */
  w6  = (w11*w14);
  /* #40: @15 = @7[2] */
  for (rr=(&w15), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #41: @19 = @3[2] */
  for (rr=(&w19), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #42: @20 = (@15*@19) */
  w20  = (w15*w19);
  /* #43: @6 = (@6-@20) */
  w6 -= w20;
  /* #44: @20 = @3[1] */
  for (rr=(&w20), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #45: @21 = (@15*@20) */
  w21  = (w15*w20);
  /* #46: @22 = @7[0] */
  for (rr=(&w22), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #47: @23 = (@22*@14) */
  w23  = (w22*w14);
  /* #48: @21 = (@21-@23) */
  w21 -= w23;
  /* #49: @23 = (@22*@19) */
  w23  = (w22*w19);
  /* #50: @24 = (@11*@20) */
  w24  = (w11*w20);
  /* #51: @23 = (@23-@24) */
  w23 -= w24;
  /* #52: @18 = vertcat(@6, @21, @23) */
  rr=w18;
  *rr++ = w6;
  *rr++ = w21;
  *rr++ = w23;
  /* #53: @8 = (@8+@18) */
  for (i=0, rr=w8, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #54: @6 = 0.000175 */
  w6 = 1.7500000000000000e-04;
  /* #55: @21 = 1e-08 */
  w21 = 1.0000000000000000e-08;
  /* #56: @23 = input[2][0] */
  w23 = arg[2] ? arg[2][0] : 0;
  /* #57: @21 = (@21+@23) */
  w21 += w23;
  /* #58: @24 = 5.84e-06 */
  w24 = 5.8400000000000000e-06;
  /* #59: @21 = (@21/@24) */
  w21 /= w24;
  /* #60: @21 = sqrt(@21) */
  w21 = sqrt( w21 );
  /* #61: @24 = (@6*@21) */
  w24  = (w6*w21);
  /* #62: @25 = 0.666667 */
  w25 = 6.6666666666666663e-01;
  /* #63: @26 = input[1][0] */
  casadi_copy(arg[1], 10, w26);
  /* #64: {@18, @27, @28} = vertsplit(@26) */
  casadi_copy(w26, 3, w18);
  casadi_copy(w26+3, 3, w27);
  casadi_copy(w26+6, 4, w28);
  /* #65: @27 = (@25*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #66: @29 = (@24*@27) */
  for (i=0, rr=w29, cs=w27; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #67: @30 = (@8*@29) */
  for (i=0, rr=w30, cr=w8, cs=w29; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #68: @30 = (@30-@29) */
  for (i=0, rr=w30, cs=w29; i<3; ++i) (*rr++) -= (*cs++);
  /* #69: @30 = (@30+@18) */
  for (i=0, rr=w30, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #70: output[0][0] = @30 */
  casadi_copy(w30, 3, res[0]);
  /* #71: @31 = zeros(4x1) */
  casadi_clear(w31, 4);
  /* #72: @30 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+1 : 0, 3, w30);
  /* #73: @24 = @30[1] */
  for (rr=(&w24), ss=w30+1; ss!=w30+2; ss+=1) *rr++ = *ss;
  /* #74: @25 = 0.5 */
  w25 = 5.0000000000000000e-01;
  /* #75: @28 = (@25*@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w25*(*cs++));
  /* #76: {@25, @18} = vertsplit(@28) */
  w25 = w28[0];
  casadi_copy(w28+1, 3, w18);
  /* #77: {@32, @33, @34} = vertsplit(@18) */
  w32 = w18[0];
  w33 = w18[1];
  w34 = w18[2];
  /* #78: @35 = (@24*@34) */
  w35  = (w24*w34);
  /* #79: @36 = @30[2] */
  for (rr=(&w36), ss=w30+2; ss!=w30+3; ss+=1) *rr++ = *ss;
  /* #80: @37 = (@36*@33) */
  w37  = (w36*w33);
  /* #81: @35 = (@35-@37) */
  w35 -= w37;
  /* #82: (@31[1] += @35) */
  for (rr=w31+1, ss=(&w35); rr!=w31+2; rr+=1) *rr += *ss++;
  /* #83: @35 = @30[0] */
  for (rr=(&w35), ss=w30+0; ss!=w30+1; ss+=1) *rr++ = *ss;
  /* #84: @37 = (@35*@33) */
  w37  = (w35*w33);
  /* #85: @24 = (@24*@32) */
  w24 *= w32;
  /* #86: @37 = (@37-@24) */
  w37 -= w24;
  /* #87: (@31[3] += @37) */
  for (rr=w31+3, ss=(&w37); rr!=w31+4; rr+=1) *rr += *ss++;
  /* #88: @36 = (@36*@32) */
  w36 *= w32;
  /* #89: @35 = (@35*@34) */
  w35 *= w34;
  /* #90: @36 = (@36-@35) */
  w36 -= w35;
  /* #91: (@31[2] += @36) */
  for (rr=w31+2, ss=(&w36); rr!=w31+3; rr+=1) *rr += *ss++;
  /* #92: @36 = dot(@30, @18) */
  w36 = casadi_dot(3, w30, w18);
  /* #93: (@31[0] += @36) */
  for (rr=w31+0, ss=(&w36); rr!=w31+1; rr+=1) *rr += *ss++;
  /* #94: @30 = (@25*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #95: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #96: (@31[1:4] += @30) */
  for (rr=w31+1, ss=w30; rr!=w31+4; rr+=1) *rr += *ss++;
  /* #97: @30 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w30);
  /* #98: @29 = (@30*@29) */
  for (i=0, rr=w29, cr=w30, cs=w29; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #99: @38 = (@23*@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++)  = (w23*(*cs++));
  /* #100: @29 = (@29+@38) */
  for (i=0, rr=w29, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #101: @38 = (-@29) */
  for (i=0, rr=w38, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #102: @23 = dot(@16, @38) */
  w23 = casadi_dot(3, w16, w38);
  /* #103: @17 = (@17*@23) */
  for (i=0, rr=w17; i<3; ++i) (*rr++) *= w23;
  /* #104: (@31[1:4] += @17) */
  for (rr=w31+1, ss=w17; rr!=w31+4; rr+=1) *rr += *ss++;
  /* #105: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #106: {@23, @36, @35} = vertsplit(@29) */
  w23 = w29[0];
  w36 = w29[1];
  w35 = w29[2];
  /* #107: @37 = (@19*@35) */
  w37  = (w19*w35);
  /* #108: @24 = (@14*@36) */
  w24  = (w14*w36);
  /* #109: @37 = (@37-@24) */
  w37 -= w24;
  /* #110: (@17[0] += @37) */
  for (rr=w17+0, ss=(&w37); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #111: @37 = (@20*@36) */
  w37  = (w20*w36);
  /* #112: @19 = (@19*@23) */
  w19 *= w23;
  /* #113: @37 = (@37-@19) */
  w37 -= w19;
  /* #114: (@17[2] += @37) */
  for (rr=w17+2, ss=(&w37); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #115: @14 = (@14*@23) */
  w14 *= w23;
  /* #116: @20 = (@20*@35) */
  w20 *= w35;
  /* #117: @14 = (@14-@20) */
  w14 -= w20;
  /* #118: (@17[1] += @14) */
  for (rr=w17+1, ss=(&w14); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #119: @16 = (@5*@29) */
  for (i=0, rr=w16, cs=w29; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #120: @17 = (@17+@16) */
  for (i=0, rr=w17, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #121: {@5, @14, @20} = vertsplit(@17) */
  w5 = w17[0];
  w14 = w17[1];
  w20 = w17[2];
  /* #122: @37 = (@12*@20) */
  w37  = (w12*w20);
  /* #123: @19 = (@9*@14) */
  w19  = (w9*w14);
  /* #124: @37 = (@37-@19) */
  w37 -= w19;
  /* #125: (@31[1] += @37) */
  for (rr=w31+1, ss=(&w37); rr!=w31+2; rr+=1) *rr += *ss++;
  /* #126: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #127: @12 = (@12*@5) */
  w12 *= w5;
  /* #128: @14 = (@14-@12) */
  w14 -= w12;
  /* #129: (@31[3] += @14) */
  for (rr=w31+3, ss=(&w14); rr!=w31+4; rr+=1) *rr += *ss++;
  /* #130: @9 = (@9*@5) */
  w9 *= w5;
  /* #131: @13 = (@13*@20) */
  w13 *= w20;
  /* #132: @9 = (@9-@13) */
  w9 -= w13;
  /* #133: (@31[2] += @9) */
  for (rr=w31+2, ss=(&w9); rr!=w31+3; rr+=1) *rr += *ss++;
  /* #134: @9 = dot(@2, @17) */
  w9 = casadi_dot(3, w2, w17);
  /* #135: (@31[0] += @9) */
  for (rr=w31+0, ss=(&w9); rr!=w31+1; rr+=1) *rr += *ss++;
  /* #136: @9 = (2.*@1) */
  w9 = (2.* w1 );
  /* #137: @3 = (@3/@4) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) /= w4;
  /* #138: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) *rr++ = (- *cs++ );
  /* #139: @28 = zeros(4x1) */
  casadi_clear(w28, 4);
  /* #140: @13 = (@15*@36) */
  w13  = (w15*w36);
  /* #141: @20 = (@11*@35) */
  w20  = (w11*w35);
  /* #142: @13 = (@13-@20) */
  w13 -= w20;
  /* #143: (@28[1] += @13) */
  for (rr=w28+1, ss=(&w13); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #144: @35 = (@22*@35) */
  w35  = (w22*w35);
  /* #145: @15 = (@15*@23) */
  w15 *= w23;
  /* #146: @35 = (@35-@15) */
  w35 -= w15;
  /* #147: (@28[2] += @35) */
  for (rr=w28+2, ss=(&w35); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #148: @11 = (@11*@23) */
  w11 *= w23;
  /* #149: @22 = (@22*@36) */
  w22 *= w36;
  /* #150: @11 = (@11-@22) */
  w11 -= w22;
  /* #151: (@28[3] += @11) */
  for (rr=w28+3, ss=(&w11); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #152: @2 = (@10*@29) */
  for (i=0, rr=w2, cs=w29; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #153: @2 = (-@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) *rr++ = (- *cs++ );
  /* #154: (@28[1:4] += @2) */
  for (rr=w28+1, ss=w2; rr!=w28+4; rr+=1) *rr += *ss++;
  /* #155: @10 = dot(@7, @29) */
  w10 = casadi_dot(3, w7, w29);
  /* #156: (@28[0] += @10) */
  for (rr=w28+0, ss=(&w10); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #157: @10 = dot(@3, @28) */
  w10 = casadi_dot(4, w3, w28);
  /* #158: @9 = (@9*@10) */
  w9 *= w10;
  /* #159: @9 = (@9/@1) */
  w9 /= w1;
  /* #160: @3 = (@9*@0) */
  for (i=0, rr=w3, cs=w0; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #161: @31 = (@31+@3) */
  for (i=0, rr=w31, cs=w3; i<4; ++i) (*rr++) += (*cs++);
  /* #162: @28 = (@28/@4) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w4;
  /* #163: {@4, @7} = vertsplit(@28) */
  w4 = w28[0];
  casadi_copy(w28+1, 3, w7);
  /* #164: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) *rr++ = (- *cs++ );
  /* #165: (@31[1:4] += @7) */
  for (rr=w31+1, ss=w7; rr!=w31+4; rr+=1) *rr += *ss++;
  /* #166: (@31[0] += @4) */
  for (rr=w31+0, ss=(&w4); rr!=w31+1; rr+=1) *rr += *ss++;
  /* #167: output[0][1] = @31 */
  if (res[0]) casadi_copy(w31, 4, res[0]+3);
  /* #168: @4 = 171233 */
  w4 = 1.7123287671232875e+05;
  /* #169: @7 = (@30*@8) */
  for (i=0, rr=w7, cr=w30, cs=w8; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #170: @30 = (@30-@7) */
  for (i=0, rr=w30, cs=w7; i<3; ++i) (*rr++) -= (*cs++);
  /* #171: @7 = (-@27) */
  for (i=0, rr=w7, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #172: @9 = dot(@30, @7) */
  w9 = casadi_dot(3, w30, w7);
  /* #173: @6 = (@6*@9) */
  w6 *= w9;
  /* #174: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #175: @6 = (@6/@21) */
  w6 /= w21;
  /* #176: @4 = (@4*@6) */
  w4 *= w6;
  /* #177: @6 = dot(@8, @27) */
  w6 = casadi_dot(3, w8, w27);
  /* #178: @4 = (@4+@6) */
  w4 += w6;
  /* #179: output[0][2] = @4 */
  if (res[0]) res[0][7] = w4;
  /* #180: @8 = zeros(3x1) */
  casadi_clear(w8, 3);
  /* #181: @4 = @0[3] */
  for (rr=(&w4), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #182: @6 = (@4*@33) */
  w6  = (w4*w33);
  /* #183: @21 = @0[2] */
  for (rr=(&w21), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #184: @9 = (@21*@34) */
  w9  = (w21*w34);
  /* #185: @6 = (@6-@9) */
  w6 -= w9;
  /* #186: (@8[0] += @6) */
  for (rr=w8+0, ss=(&w6); rr!=w8+1; rr+=1) *rr += *ss++;
  /* #187: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #188: @34 = (@6*@34) */
  w34  = (w6*w34);
  /* #189: @4 = (@4*@32) */
  w4 *= w32;
  /* #190: @34 = (@34-@4) */
  w34 -= w4;
  /* #191: (@8[1] += @34) */
  for (rr=w8+1, ss=(&w34); rr!=w8+2; rr+=1) *rr += *ss++;
  /* #192: @21 = (@21*@32) */
  w21 *= w32;
  /* #193: @6 = (@6*@33) */
  w6 *= w33;
  /* #194: @21 = (@21-@6) */
  w21 -= w6;
  /* #195: (@8[2] += @21) */
  for (rr=w8+2, ss=(&w21); rr!=w8+3; rr+=1) *rr += *ss++;
  /* #196: @21 = @0[0] */
  for (rr=(&w21), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #197: @18 = (@21*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #198: @8 = (@8+@18) */
  for (i=0, rr=w8, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #199: @18 = @0[1:4] */
  for (rr=w18, ss=w0+1; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #200: @18 = (@25*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #201: @8 = (@8-@18) */
  for (i=0, rr=w8, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #202: output[0][3] = @8 */
  if (res[0]) casadi_copy(w8, 3, res[0]+8);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 80;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
