/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {21, 1, 0, 18, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};

static const casadi_real casadi_c0[3] = {0., 0., 1.};

/* drone_simple_drag_expl_vde_adj:(i0[17],i1[17],i2[4],i3[])->(o0[21x1,18nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+17, *w2=w+20, *w3=w+23, *w4=w+27, w5, *w6=w+31, *w7=w+34, w8, w9, *w10=w+40, w11, w12, w13, w14, w15, w16, *w17=w+49, *w18=w+52, *w19=w+56, *w20=w+59, *w21=w+62, w22, w23, w24, w25, w26, w27, w28, *w29=w+72, w30, w31, w32, w33, w34, *w35=w+80, w36;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 17, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  casadi_copy(w0+10, 3, w4);
  w5 = w0[13];
  casadi_copy(w0+14, 3, w6);
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @7 = zeros(4x1) */
  casadi_clear(w7, 4);
  /* #4: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #5: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @9 = 0.5 */
  w9 = 5.0000000000000000e-01;
  /* #7: @3 = (@9*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #8: {@9, @10} = vertsplit(@3) */
  w9 = w3[0];
  casadi_copy(w3+1, 3, w10);
  /* #9: {@11, @12, @13} = vertsplit(@10) */
  w11 = w10[0];
  w12 = w10[1];
  w13 = w10[2];
  /* #10: @14 = (@8*@13) */
  w14  = (w8*w13);
  /* #11: @15 = @1[2] */
  for (rr=(&w15), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #12: @16 = (@15*@12) */
  w16  = (w15*w12);
  /* #13: @14 = (@14-@16) */
  w14 -= w16;
  /* #14: (@7[1] += @14) */
  for (rr=w7+1, ss=(&w14); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #15: @14 = @1[0] */
  for (rr=(&w14), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @16 = (@14*@12) */
  w16  = (w14*w12);
  /* #17: @8 = (@8*@11) */
  w8 *= w11;
  /* #18: @16 = (@16-@8) */
  w16 -= w8;
  /* #19: (@7[3] += @16) */
  for (rr=w7+3, ss=(&w16); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #20: @15 = (@15*@11) */
  w15 *= w11;
  /* #21: @14 = (@14*@13) */
  w14 *= w13;
  /* #22: @15 = (@15-@14) */
  w15 -= w14;
  /* #23: (@7[2] += @15) */
  for (rr=w7+2, ss=(&w15); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #24: @15 = dot(@1, @10) */
  w15 = casadi_dot(3, w1, w10);
  /* #25: (@7[0] += @15) */
  for (rr=w7+0, ss=(&w15); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #26: @1 = (@9*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #27: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #28: (@7[1:4] += @1) */
  for (rr=w7+1, ss=w1; rr!=w7+4; rr+=1) *rr += *ss++;
  /* #29: @1 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w1);
  /* #30: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #31: @15 = @3[0] */
  for (rr=(&w15), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #32: @17 = @3[1:4] */
  for (rr=w17, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #33: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) *rr++ = (- *cs++ );
  /* #34: @18 = vertcat(@15, @17) */
  rr=w18;
  *rr++ = w15;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #35: @15 = ||@3||_F */
  w15 = sqrt(casadi_dot(4, w3, w3));
  /* #36: @14 = sq(@15) */
  w14 = casadi_sq( w15 );
  /* #37: @18 = (@18/@14) */
  for (i=0, rr=w18; i<4; ++i) (*rr++) /= w14;
  /* #38: @17 = @18[1:4] */
  for (rr=w17, ss=w18+1; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #39: @16 = input[0][4] */
  w16 = arg[0] ? arg[0][13] : 0;
  /* #40: @19 = (@16*@2) */
  for (i=0, rr=w19, cs=w2; i<3; ++i) (*rr++)  = (w16*(*cs++));
  /* #41: @20 = (-@19) */
  for (i=0, rr=w20, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #42: @16 = dot(@17, @20) */
  w16 = casadi_dot(3, w17, w20);
  /* #43: @20 = (@1*@16) */
  for (i=0, rr=w20, cr=w1; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #44: (@7[1:4] += @20) */
  for (rr=w7+1, ss=w20; rr!=w7+4; rr+=1) *rr += *ss++;
  /* #45: @20 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w20);
  /* #46: @16 = @20[1] */
  for (rr=(&w16), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #47: @21 = zeros(3x1) */
  casadi_clear(w21, 3);
  /* #48: @8 = @18[2] */
  for (rr=(&w8), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #49: {@22, @23, @24} = vertsplit(@19) */
  w22 = w19[0];
  w23 = w19[1];
  w24 = w19[2];
  /* #50: @25 = (@8*@24) */
  w25  = (w8*w24);
  /* #51: @26 = @18[3] */
  for (rr=(&w26), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #52: @27 = (@26*@23) */
  w27  = (w26*w23);
  /* #53: @25 = (@25-@27) */
  w25 -= w27;
  /* #54: (@21[0] += @25) */
  for (rr=w21+0, ss=(&w25); rr!=w21+1; rr+=1) *rr += *ss++;
  /* #55: @25 = @18[1] */
  for (rr=(&w25), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #56: @27 = (@25*@23) */
  w27  = (w25*w23);
  /* #57: @28 = (@8*@22) */
  w28  = (w8*w22);
  /* #58: @27 = (@27-@28) */
  w27 -= w28;
  /* #59: (@21[2] += @27) */
  for (rr=w21+2, ss=(&w27); rr!=w21+3; rr+=1) *rr += *ss++;
  /* #60: @27 = (@26*@22) */
  w27  = (w26*w22);
  /* #61: @28 = (@25*@24) */
  w28  = (w25*w24);
  /* #62: @27 = (@27-@28) */
  w27 -= w28;
  /* #63: (@21[1] += @27) */
  for (rr=w21+1, ss=(&w27); rr!=w21+2; rr+=1) *rr += *ss++;
  /* #64: @27 = @18[0] */
  for (rr=(&w27), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #65: @29 = (@27*@19) */
  for (i=0, rr=w29, cs=w19; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #66: @21 = (@21+@29) */
  for (i=0, rr=w21, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #67: {@28, @30, @31} = vertsplit(@21) */
  w28 = w21[0];
  w30 = w21[1];
  w31 = w21[2];
  /* #68: @32 = (@16*@31) */
  w32  = (w16*w31);
  /* #69: @33 = @20[2] */
  for (rr=(&w33), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #70: @34 = (@33*@30) */
  w34  = (w33*w30);
  /* #71: @32 = (@32-@34) */
  w32 -= w34;
  /* #72: (@7[1] += @32) */
  for (rr=w7+1, ss=(&w32); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #73: @32 = @20[0] */
  for (rr=(&w32), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #74: @30 = (@32*@30) */
  w30  = (w32*w30);
  /* #75: @34 = (@16*@28) */
  w34  = (w16*w28);
  /* #76: @30 = (@30-@34) */
  w30 -= w34;
  /* #77: (@7[3] += @30) */
  for (rr=w7+3, ss=(&w30); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #78: @28 = (@33*@28) */
  w28  = (w33*w28);
  /* #79: @31 = (@32*@31) */
  w31  = (w32*w31);
  /* #80: @28 = (@28-@31) */
  w28 -= w31;
  /* #81: (@7[2] += @28) */
  for (rr=w7+2, ss=(&w28); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #82: @20 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w20);
  /* #83: @28 = dot(@20, @21) */
  w28 = casadi_dot(3, w20, w21);
  /* #84: (@7[0] += @28) */
  for (rr=w7+0, ss=(&w28); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #85: @28 = (2.*@15) */
  w28 = (2.* w15 );
  /* #86: @18 = (@18/@14) */
  for (i=0, rr=w18; i<4; ++i) (*rr++) /= w14;
  /* #87: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) *rr++ = (- *cs++ );
  /* #88: @35 = zeros(4x1) */
  casadi_clear(w35, 4);
  /* #89: @31 = @3[0] */
  for (rr=(&w31), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #90: @20 = (@20*@31) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w31;
  /* #91: @31 = @3[2] */
  for (rr=(&w31), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #92: @30 = (@31*@33) */
  w30  = (w31*w33);
  /* #93: @34 = @3[3] */
  for (rr=(&w34), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #94: @36 = (@34*@16) */
  w36  = (w34*w16);
  /* #95: @30 = (@30-@36) */
  w30 -= w36;
  /* #96: @34 = (@34*@32) */
  w34 *= w32;
  /* #97: @36 = @3[1] */
  for (rr=(&w36), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #98: @33 = (@36*@33) */
  w33  = (w36*w33);
  /* #99: @34 = (@34-@33) */
  w34 -= w33;
  /* #100: @36 = (@36*@16) */
  w36 *= w16;
  /* #101: @31 = (@31*@32) */
  w31 *= w32;
  /* #102: @36 = (@36-@31) */
  w36 -= w31;
  /* #103: @21 = vertcat(@30, @34, @36) */
  rr=w21;
  *rr++ = w30;
  *rr++ = w34;
  *rr++ = w36;
  /* #104: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #105: @30 = @20[2] */
  for (rr=(&w30), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #106: @34 = (@30*@23) */
  w34  = (w30*w23);
  /* #107: @36 = @20[1] */
  for (rr=(&w36), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #108: @31 = (@36*@24) */
  w31  = (w36*w24);
  /* #109: @34 = (@34-@31) */
  w34 -= w31;
  /* #110: (@35[1] += @34) */
  for (rr=w35+1, ss=(&w34); rr!=w35+2; rr+=1) *rr += *ss++;
  /* #111: @34 = @20[0] */
  for (rr=(&w34), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #112: @24 = (@34*@24) */
  w24  = (w34*w24);
  /* #113: @31 = (@30*@22) */
  w31  = (w30*w22);
  /* #114: @24 = (@24-@31) */
  w24 -= w31;
  /* #115: (@35[2] += @24) */
  for (rr=w35+2, ss=(&w24); rr!=w35+3; rr+=1) *rr += *ss++;
  /* #116: @22 = (@36*@22) */
  w22  = (w36*w22);
  /* #117: @23 = (@34*@23) */
  w23  = (w34*w23);
  /* #118: @22 = (@22-@23) */
  w22 -= w23;
  /* #119: (@35[3] += @22) */
  for (rr=w35+3, ss=(&w22); rr!=w35+4; rr+=1) *rr += *ss++;
  /* #120: @21 = @3[1:4] */
  for (rr=w21, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #121: @22 = dot(@21, @1) */
  w22 = casadi_dot(3, w21, w1);
  /* #122: @21 = (@22*@19) */
  for (i=0, rr=w21, cs=w19; i<3; ++i) (*rr++)  = (w22*(*cs++));
  /* #123: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (- *cs++ );
  /* #124: (@35[1:4] += @21) */
  for (rr=w35+1, ss=w21; rr!=w35+4; rr+=1) *rr += *ss++;
  /* #125: @23 = dot(@20, @19) */
  w23 = casadi_dot(3, w20, w19);
  /* #126: (@35[0] += @23) */
  for (rr=w35+0, ss=(&w23); rr!=w35+1; rr+=1) *rr += *ss++;
  /* #127: @23 = dot(@18, @35) */
  w23 = casadi_dot(4, w18, w35);
  /* #128: @28 = (@28*@23) */
  w28 *= w23;
  /* #129: @28 = (@28/@15) */
  w28 /= w15;
  /* #130: @18 = (@28*@3) */
  for (i=0, rr=w18, cs=w3; i<4; ++i) (*rr++)  = (w28*(*cs++));
  /* #131: @7 = (@7+@18) */
  for (i=0, rr=w7, cs=w18; i<4; ++i) (*rr++) += (*cs++);
  /* #132: @35 = (@35/@14) */
  for (i=0, rr=w35; i<4; ++i) (*rr++) /= w14;
  /* #133: {@14, @19} = vertsplit(@35) */
  w14 = w35[0];
  casadi_copy(w35+1, 3, w19);
  /* #134: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #135: (@7[1:4] += @19) */
  for (rr=w7+1, ss=w19; rr!=w7+4; rr+=1) *rr += *ss++;
  /* #136: (@7[0] += @14) */
  for (rr=w7+0, ss=(&w14); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #137: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 4, res[0]+3);
  /* #138: @14 = 10 */
  w14 = 10.;
  /* #139: @4 = (@14*@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #140: @19 = (-@4) */
  for (i=0, rr=w19, cs=w4; i<3; ++i) *rr++ = (- *cs++ );
  /* #141: @14 = @3[3] */
  for (rr=(&w14), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #142: @28 = (@14*@12) */
  w28  = (w14*w12);
  /* #143: @15 = @3[2] */
  for (rr=(&w15), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #144: @23 = (@15*@13) */
  w23  = (w15*w13);
  /* #145: @28 = (@28-@23) */
  w28 -= w23;
  /* #146: (@19[0] += @28) */
  for (rr=w19+0, ss=(&w28); rr!=w19+1; rr+=1) *rr += *ss++;
  /* #147: @28 = @3[1] */
  for (rr=(&w28), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #148: @13 = (@28*@13) */
  w13  = (w28*w13);
  /* #149: @14 = (@14*@11) */
  w14 *= w11;
  /* #150: @13 = (@13-@14) */
  w13 -= w14;
  /* #151: (@19[1] += @13) */
  for (rr=w19+1, ss=(&w13); rr!=w19+2; rr+=1) *rr += *ss++;
  /* #152: @15 = (@15*@11) */
  w15 *= w11;
  /* #153: @28 = (@28*@12) */
  w28 *= w12;
  /* #154: @15 = (@15-@28) */
  w15 -= w28;
  /* #155: (@19[2] += @15) */
  for (rr=w19+2, ss=(&w15); rr!=w19+3; rr+=1) *rr += *ss++;
  /* #156: @15 = @3[0] */
  for (rr=(&w15), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #157: @10 = (@15*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #158: @19 = (@19+@10) */
  for (i=0, rr=w19, cs=w10; i<3; ++i) (*rr++) += (*cs++);
  /* #159: @10 = @3[1:4] */
  for (rr=w10, ss=w3+1; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #160: @10 = (@9*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #161: @19 = (@19-@10) */
  for (i=0, rr=w19, cs=w10; i<3; ++i) (*rr++) -= (*cs++);
  /* #162: output[0][2] = @19 */
  if (res[0]) casadi_copy(w19, 3, res[0]+7);
  /* #163: @20 = (@27*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #164: @17 = (@22*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w22*(*cs++));
  /* #165: @20 = (@20-@17) */
  for (i=0, rr=w20, cs=w17; i<3; ++i) (*rr++) -= (*cs++);
  /* #166: @22 = (@36*@26) */
  w22  = (w36*w26);
  /* #167: @27 = (@30*@8) */
  w27  = (w30*w8);
  /* #168: @22 = (@22-@27) */
  w22 -= w27;
  /* #169: @30 = (@30*@25) */
  w30 *= w25;
  /* #170: @26 = (@34*@26) */
  w26  = (w34*w26);
  /* #171: @30 = (@30-@26) */
  w30 -= w26;
  /* #172: @34 = (@34*@8) */
  w34 *= w8;
  /* #173: @36 = (@36*@25) */
  w36 *= w25;
  /* #174: @34 = (@34-@36) */
  w34 -= w36;
  /* #175: @17 = vertcat(@22, @30, @34) */
  rr=w17;
  *rr++ = w22;
  *rr++ = w30;
  *rr++ = w34;
  /* #176: @20 = (@20+@17) */
  for (i=0, rr=w20, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #177: @22 = dot(@20, @2) */
  w22 = casadi_dot(3, w20, w2);
  /* #178: output[0][3] = @22 */
  if (res[0]) res[0][10] = w22;
  /* #179: output[0][4] = @4 */
  if (res[0]) casadi_copy(w4, 3, res[0]+11);
  /* #180: output[0][5] = @5 */
  if (res[0]) res[0][14] = w5;
  /* #181: output[0][6] = @6 */
  if (res[0]) casadi_copy(w6, 3, res[0]+15);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 85;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
