/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {-5.5759999999999998e-01, -5.1580000000000004e-01, -2.0910000000000001e-01};
static const casadi_real casadi_c2[3] = {0., 0., 9.8000000000000007e+00};

/* drone_simple_drag_expl_ode_fun:(i0[17],i1[4],i2[])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, *w2=w+4, w3, *w4=w+9, *w5=w+12, w6, *w7=w+17, w8, w9, w10, w11, w12, w13, *w14=w+26, *w15=w+29, *w16=w+32, *w17=w+36, w18, *w19=w+41;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][13] : 0;
  /* #3: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w2);
  /* #4: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #5: @4 = @2[1:4] */
  for (rr=w4, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #6: @4 = (-@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) *rr++ = (- *cs++ );
  /* #7: @5 = vertcat(@3, @4) */
  rr=w5;
  *rr++ = w3;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #8: @3 = ||@2||_F */
  w3 = sqrt(casadi_dot(4, w2, w2));
  /* #9: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #10: @5 = (@5/@3) */
  for (i=0, rr=w5; i<4; ++i) (*rr++) /= w3;
  /* #11: @3 = @5[0] */
  for (rr=(&w3), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #12: @4 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w4);
  /* #13: @6 = @2[0] */
  for (rr=(&w6), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #14: @4 = (@4*@6) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) *= w6;
  /* #15: @6 = @2[2] */
  for (rr=(&w6), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #16: @7 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w7);
  /* #17: @8 = @7[2] */
  for (rr=(&w8), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #18: @9 = (@6*@8) */
  w9  = (w6*w8);
  /* #19: @10 = @2[3] */
  for (rr=(&w10), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #20: @11 = @7[1] */
  for (rr=(&w11), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #21: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #22: @9 = (@9-@12) */
  w9 -= w12;
  /* #23: @12 = @7[0] */
  for (rr=(&w12), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #24: @10 = (@10*@12) */
  w10 *= w12;
  /* #25: @13 = @2[1] */
  for (rr=(&w13), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #26: @8 = (@13*@8) */
  w8  = (w13*w8);
  /* #27: @10 = (@10-@8) */
  w10 -= w8;
  /* #28: @13 = (@13*@11) */
  w13 *= w11;
  /* #29: @6 = (@6*@12) */
  w6 *= w12;
  /* #30: @13 = (@13-@6) */
  w13 -= w6;
  /* #31: @7 = vertcat(@9, @10, @13) */
  rr=w7;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w13;
  /* #32: @4 = (@4+@7) */
  for (i=0, rr=w4, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #33: @7 = (@3*@4) */
  for (i=0, rr=w7, cs=w4; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #34: @14 = @2[1:4] */
  for (rr=w14, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #35: @15 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w15);
  /* #36: @3 = dot(@14, @15) */
  w3 = casadi_dot(3, w14, w15);
  /* #37: @14 = @5[1:4] */
  for (rr=w14, ss=w5+1; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #38: @14 = (@3*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #39: @7 = (@7-@14) */
  for (i=0, rr=w7, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #40: @3 = @4[1] */
  for (rr=(&w3), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #41: @9 = @5[3] */
  for (rr=(&w9), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #42: @10 = (@3*@9) */
  w10  = (w3*w9);
  /* #43: @13 = @4[2] */
  for (rr=(&w13), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #44: @6 = @5[2] */
  for (rr=(&w6), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #45: @12 = (@13*@6) */
  w12  = (w13*w6);
  /* #46: @10 = (@10-@12) */
  w10 -= w12;
  /* #47: @12 = @5[1] */
  for (rr=(&w12), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #48: @13 = (@13*@12) */
  w13 *= w12;
  /* #49: @11 = @4[0] */
  for (rr=(&w11), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #50: @9 = (@11*@9) */
  w9  = (w11*w9);
  /* #51: @13 = (@13-@9) */
  w13 -= w9;
  /* #52: @11 = (@11*@6) */
  w11 *= w6;
  /* #53: @3 = (@3*@12) */
  w3 *= w12;
  /* #54: @11 = (@11-@3) */
  w11 -= w3;
  /* #55: @4 = vertcat(@10, @13, @11) */
  rr=w4;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w11;
  /* #56: @7 = (@7+@4) */
  for (i=0, rr=w7, cs=w4; i<3; ++i) (*rr++) += (*cs++);
  /* #57: @7 = (@1*@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #58: @1 = @2[0] */
  for (rr=(&w1), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #59: @4 = @2[1:4] */
  for (rr=w4, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #60: @4 = (-@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) *rr++ = (- *cs++ );
  /* #61: @5 = vertcat(@1, @4) */
  rr=w5;
  *rr++ = w1;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #62: @1 = ||@2||_F */
  w1 = sqrt(casadi_dot(4, w2, w2));
  /* #63: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #64: @5 = (@5/@1) */
  for (i=0, rr=w5; i<4; ++i) (*rr++) /= w1;
  /* #65: @1 = @5[0] */
  for (rr=(&w1), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #66: @10 = @2[0] */
  for (rr=(&w10), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #67: @4 = [-0.5576, -0.5158, -0.2091] */
  casadi_copy(casadi_c1, 3, w4);
  /* #68: @13 = @2[0] */
  for (rr=(&w13), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #69: @14 = @2[1:4] */
  for (rr=w14, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #70: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) *rr++ = (- *cs++ );
  /* #71: @16 = vertcat(@13, @14) */
  rr=w16;
  *rr++ = w13;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #72: @13 = ||@2||_F */
  w13 = sqrt(casadi_dot(4, w2, w2));
  /* #73: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #74: @16 = (@16/@13) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w13;
  /* #75: @13 = @16[0] */
  for (rr=(&w13), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #76: @14 = @16[1:4] */
  for (rr=w14, ss=w16+1; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #77: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) *rr++ = (- *cs++ );
  /* #78: @17 = vertcat(@13, @14) */
  rr=w17;
  *rr++ = w13;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #79: @13 = ||@16||_F */
  w13 = sqrt(casadi_dot(4, w16, w16));
  /* #80: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #81: @17 = (@17/@13) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) /= w13;
  /* #82: @13 = @17[0] */
  for (rr=(&w13), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #83: @11 = @16[0] */
  for (rr=(&w11), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #84: @14 = (@11*@0) */
  for (i=0, rr=w14, cs=w0; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #85: @11 = @16[2] */
  for (rr=(&w11), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #86: @3 = @0[2] */
  for (rr=(&w3), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #87: @12 = (@11*@3) */
  w12  = (w11*w3);
  /* #88: @6 = @16[3] */
  for (rr=(&w6), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #89: @9 = @0[1] */
  for (rr=(&w9), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #90: @8 = (@6*@9) */
  w8  = (w6*w9);
  /* #91: @12 = (@12-@8) */
  w12 -= w8;
  /* #92: @8 = @0[0] */
  for (rr=(&w8), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #93: @6 = (@6*@8) */
  w6 *= w8;
  /* #94: @18 = @16[1] */
  for (rr=(&w18), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #95: @3 = (@18*@3) */
  w3  = (w18*w3);
  /* #96: @6 = (@6-@3) */
  w6 -= w3;
  /* #97: @18 = (@18*@9) */
  w18 *= w9;
  /* #98: @11 = (@11*@8) */
  w11 *= w8;
  /* #99: @18 = (@18-@11) */
  w18 -= w11;
  /* #100: @15 = vertcat(@12, @6, @18) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w6;
  *rr++ = w18;
  /* #101: @14 = (@14+@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #102: @15 = (@13*@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #103: @19 = @16[1:4] */
  for (rr=w19, ss=w16+1; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #104: @13 = dot(@19, @0) */
  w13 = casadi_dot(3, w19, w0);
  /* #105: @19 = @17[1:4] */
  for (rr=w19, ss=w17+1; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #106: @19 = (@13*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #107: @15 = (@15-@19) */
  for (i=0, rr=w15, cs=w19; i<3; ++i) (*rr++) -= (*cs++);
  /* #108: @13 = @14[1] */
  for (rr=(&w13), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #109: @12 = @17[3] */
  for (rr=(&w12), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #110: @6 = (@13*@12) */
  w6  = (w13*w12);
  /* #111: @18 = @14[2] */
  for (rr=(&w18), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #112: @11 = @17[2] */
  for (rr=(&w11), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #113: @8 = (@18*@11) */
  w8  = (w18*w11);
  /* #114: @6 = (@6-@8) */
  w6 -= w8;
  /* #115: @8 = @17[1] */
  for (rr=(&w8), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #116: @18 = (@18*@8) */
  w18 *= w8;
  /* #117: @9 = @14[0] */
  for (rr=(&w9), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #118: @12 = (@9*@12) */
  w12  = (w9*w12);
  /* #119: @18 = (@18-@12) */
  w18 -= w12;
  /* #120: @9 = (@9*@11) */
  w9 *= w11;
  /* #121: @13 = (@13*@8) */
  w13 *= w8;
  /* #122: @9 = (@9-@13) */
  w9 -= w13;
  /* #123: @14 = vertcat(@6, @18, @9) */
  rr=w14;
  *rr++ = w6;
  *rr++ = w18;
  *rr++ = w9;
  /* #124: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #125: @4 = (@4*@15) */
  for (i=0, rr=w4, cs=w15; i<3; ++i) (*rr++) *= (*cs++);
  /* #126: @14 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w14);
  /* #127: @6 = -0.0145 */
  w6 = -1.4500000000000001e-02;
  /* #128: @18 = @15[0] */
  for (rr=(&w18), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #129: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #130: @9 = @15[1] */
  for (rr=(&w9), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #131: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #132: @18 = (@18+@9) */
  w18 += w9;
  /* #133: @6 = (@6*@18) */
  w6 *= w18;
  /* #134: @18 = -0.0391 */
  w18 = -3.9100000000000003e-02;
  /* #135: @9 = @15[2] */
  for (rr=(&w9), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #136: @18 = (@18*@9) */
  w18 *= w9;
  /* #137: @9 = @15[2] */
  for (rr=(&w9), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #138: @18 = (@18*@9) */
  w18 *= w9;
  /* #139: @6 = (@6+@18) */
  w6 += w18;
  /* #140: @14 = (@14*@6) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) *= w6;
  /* #141: @4 = (@4+@14) */
  for (i=0, rr=w4, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #142: @14 = (@10*@4) */
  for (i=0, rr=w14, cs=w4; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #143: @10 = @2[2] */
  for (rr=(&w10), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #144: @6 = @4[2] */
  for (rr=(&w6), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #145: @18 = (@10*@6) */
  w18  = (w10*w6);
  /* #146: @9 = @2[3] */
  for (rr=(&w9), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #147: @13 = @4[1] */
  for (rr=(&w13), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #148: @8 = (@9*@13) */
  w8  = (w9*w13);
  /* #149: @18 = (@18-@8) */
  w18 -= w8;
  /* #150: @8 = @4[0] */
  for (rr=(&w8), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #151: @9 = (@9*@8) */
  w9 *= w8;
  /* #152: @11 = @2[1] */
  for (rr=(&w11), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #153: @6 = (@11*@6) */
  w6  = (w11*w6);
  /* #154: @9 = (@9-@6) */
  w9 -= w6;
  /* #155: @11 = (@11*@13) */
  w11 *= w13;
  /* #156: @10 = (@10*@8) */
  w10 *= w8;
  /* #157: @11 = (@11-@10) */
  w11 -= w10;
  /* #158: @15 = vertcat(@18, @9, @11) */
  rr=w15;
  *rr++ = w18;
  *rr++ = w9;
  *rr++ = w11;
  /* #159: @14 = (@14+@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #160: @15 = (@1*@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #161: @19 = @2[1:4] */
  for (rr=w19, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #162: @1 = dot(@19, @4) */
  w1 = casadi_dot(3, w19, w4);
  /* #163: @19 = @5[1:4] */
  for (rr=w19, ss=w5+1; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #164: @19 = (@1*@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #165: @15 = (@15-@19) */
  for (i=0, rr=w15, cs=w19; i<3; ++i) (*rr++) -= (*cs++);
  /* #166: @1 = @14[1] */
  for (rr=(&w1), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #167: @18 = @5[3] */
  for (rr=(&w18), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #168: @9 = (@1*@18) */
  w9  = (w1*w18);
  /* #169: @11 = @14[2] */
  for (rr=(&w11), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #170: @10 = @5[2] */
  for (rr=(&w10), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #171: @8 = (@11*@10) */
  w8  = (w11*w10);
  /* #172: @9 = (@9-@8) */
  w9 -= w8;
  /* #173: @8 = @5[1] */
  for (rr=(&w8), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #174: @11 = (@11*@8) */
  w11 *= w8;
  /* #175: @13 = @14[0] */
  for (rr=(&w13), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #176: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #177: @11 = (@11-@18) */
  w11 -= w18;
  /* #178: @13 = (@13*@10) */
  w13 *= w10;
  /* #179: @1 = (@1*@8) */
  w1 *= w8;
  /* #180: @13 = (@13-@1) */
  w13 -= w1;
  /* #181: @14 = vertcat(@9, @11, @13) */
  rr=w14;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w13;
  /* #182: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #183: @7 = (@7+@15) */
  for (i=0, rr=w7, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #184: @15 = [0, 0, 9.8] */
  casadi_copy(casadi_c2, 3, w15);
  /* #185: @7 = (@7-@15) */
  for (i=0, rr=w7, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #186: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 3, res[0]+3);
  /* #187: @9 = 0.5 */
  w9 = 5.0000000000000000e-01;
  /* #188: @7 = @2[1:4] */
  for (rr=w7, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #189: @15 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w15);
  /* #190: @11 = dot(@7, @15) */
  w11 = casadi_dot(3, w7, w15);
  /* #191: @11 = (-@11) */
  w11 = (- w11 );
  /* #192: @13 = @2[0] */
  for (rr=(&w13), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #193: @7 = (@13*@15) */
  for (i=0, rr=w7, cs=w15; i<3; ++i) (*rr++)  = (w13*(*cs++));
  /* #194: @13 = @2[2] */
  for (rr=(&w13), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #195: @1 = @15[2] */
  for (rr=(&w1), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #196: @8 = (@13*@1) */
  w8  = (w13*w1);
  /* #197: @10 = @2[3] */
  for (rr=(&w10), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #198: @18 = @15[1] */
  for (rr=(&w18), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #199: @6 = (@10*@18) */
  w6  = (w10*w18);
  /* #200: @8 = (@8-@6) */
  w8 -= w6;
  /* #201: @6 = @15[0] */
  for (rr=(&w6), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #202: @10 = (@10*@6) */
  w10 *= w6;
  /* #203: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #204: @1 = (@12*@1) */
  w1  = (w12*w1);
  /* #205: @10 = (@10-@1) */
  w10 -= w1;
  /* #206: @12 = (@12*@18) */
  w12 *= w18;
  /* #207: @13 = (@13*@6) */
  w13 *= w6;
  /* #208: @12 = (@12-@13) */
  w12 -= w13;
  /* #209: @14 = vertcat(@8, @10, @12) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w12;
  /* #210: @7 = (@7+@14) */
  for (i=0, rr=w7, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #211: @2 = vertcat(@11, @7) */
  rr=w2;
  *rr++ = w11;
  for (i=0, cs=w7; i<3; ++i) *rr++ = *cs++;
  /* #212: @2 = (@9*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #213: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 4, res[0]+6);
  /* #214: @9 = 20 */
  w9 = 20.;
  /* #215: @7 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+14 : 0, 3, w7);
  /* #216: @7 = (@7-@15) */
  for (i=0, rr=w7, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #217: @7 = (@9*@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #218: output[0][3] = @7 */
  if (res[0]) casadi_copy(w7, 3, res[0]+10);
  /* #219: @9 = input[1][0] */
  w9 = arg[1] ? arg[1][0] : 0;
  /* #220: output[0][4] = @9 */
  if (res[0]) res[0][13] = w9;
  /* #221: @7 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w7);
  /* #222: output[0][5] = @7 */
  if (res[0]) casadi_copy(w7, 3, res[0]+14);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 44;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
