/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 0., 9.8000000000000007e+00};

/* drone_simple_drag_expl_ode_fun:(i0[10],i1[4],i2[])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, w1, *w2=w+4, w3, *w4=w+9, *w5=w+12, w6, *w7=w+17, w8, w9, w10, w11, w12, w13, *w14=w+26, *w15=w+29;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #3: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w2);
  /* #4: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #5: @4 = @2[1:4] */
  for (rr=w4, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #6: @4 = (-@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) *rr++ = (- *cs++ );
  /* #7: @5 = vertcat(@3, @4) */
  rr=w5;
  *rr++ = w3;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #8: @3 = ||@2||_F */
  w3 = sqrt(casadi_dot(4, w2, w2));
  /* #9: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #10: @5 = (@5/@3) */
  for (i=0, rr=w5; i<4; ++i) (*rr++) /= w3;
  /* #11: @3 = @5[0] */
  for (rr=(&w3), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #12: @4 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w4);
  /* #13: @6 = @2[0] */
  for (rr=(&w6), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #14: @4 = (@4*@6) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) *= w6;
  /* #15: @6 = @2[2] */
  for (rr=(&w6), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #16: @7 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w7);
  /* #17: @8 = @7[2] */
  for (rr=(&w8), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #18: @9 = (@6*@8) */
  w9  = (w6*w8);
  /* #19: @10 = @2[3] */
  for (rr=(&w10), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #20: @11 = @7[1] */
  for (rr=(&w11), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #21: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #22: @9 = (@9-@12) */
  w9 -= w12;
  /* #23: @12 = @7[0] */
  for (rr=(&w12), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #24: @10 = (@10*@12) */
  w10 *= w12;
  /* #25: @13 = @2[1] */
  for (rr=(&w13), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #26: @8 = (@13*@8) */
  w8  = (w13*w8);
  /* #27: @10 = (@10-@8) */
  w10 -= w8;
  /* #28: @13 = (@13*@11) */
  w13 *= w11;
  /* #29: @6 = (@6*@12) */
  w6 *= w12;
  /* #30: @13 = (@13-@6) */
  w13 -= w6;
  /* #31: @7 = vertcat(@9, @10, @13) */
  rr=w7;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w13;
  /* #32: @4 = (@4+@7) */
  for (i=0, rr=w4, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #33: @7 = (@3*@4) */
  for (i=0, rr=w7, cs=w4; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #34: @14 = @2[1:4] */
  for (rr=w14, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #35: @15 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w15);
  /* #36: @3 = dot(@14, @15) */
  w3 = casadi_dot(3, w14, w15);
  /* #37: @14 = @5[1:4] */
  for (rr=w14, ss=w5+1; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #38: @14 = (@3*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #39: @7 = (@7-@14) */
  for (i=0, rr=w7, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #40: @3 = @4[1] */
  for (rr=(&w3), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #41: @9 = @5[3] */
  for (rr=(&w9), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #42: @10 = (@3*@9) */
  w10  = (w3*w9);
  /* #43: @13 = @4[2] */
  for (rr=(&w13), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #44: @6 = @5[2] */
  for (rr=(&w6), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #45: @12 = (@13*@6) */
  w12  = (w13*w6);
  /* #46: @10 = (@10-@12) */
  w10 -= w12;
  /* #47: @12 = @5[1] */
  for (rr=(&w12), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #48: @13 = (@13*@12) */
  w13 *= w12;
  /* #49: @11 = @4[0] */
  for (rr=(&w11), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #50: @9 = (@11*@9) */
  w9  = (w11*w9);
  /* #51: @13 = (@13-@9) */
  w13 -= w9;
  /* #52: @11 = (@11*@6) */
  w11 *= w6;
  /* #53: @3 = (@3*@12) */
  w3 *= w12;
  /* #54: @11 = (@11-@3) */
  w11 -= w3;
  /* #55: @4 = vertcat(@10, @13, @11) */
  rr=w4;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w11;
  /* #56: @7 = (@7+@4) */
  for (i=0, rr=w7, cs=w4; i<3; ++i) (*rr++) += (*cs++);
  /* #57: @4 = (@1*@7) */
  for (i=0, rr=w4, cs=w7; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #58: @10 = 0.000175 */
  w10 = 1.7500000000000000e-04;
  /* #59: @13 = 1e-08 */
  w13 = 1.0000000000000000e-08;
  /* #60: @13 = (@13+@1) */
  w13 += w1;
  /* #61: @1 = 5.84e-06 */
  w1 = 5.8400000000000000e-06;
  /* #62: @13 = (@13/@1) */
  w13 /= w1;
  /* #63: @13 = sqrt(@13) */
  w13 = sqrt( w13 );
  /* #64: @10 = (@10*@13) */
  w10 *= w13;
  /* #65: @7 = (@0*@7) */
  for (i=0, rr=w7, cr=w0, cs=w7; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #66: @0 = (@0-@7) */
  for (i=0, rr=w0, cs=w7; i<3; ++i) (*rr++) -= (*cs++);
  /* #67: @0 = (@10*@0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #68: @4 = (@4-@0) */
  for (i=0, rr=w4, cs=w0; i<3; ++i) (*rr++) -= (*cs++);
  /* #69: @10 = 1.5 */
  w10 = 1.5000000000000000e+00;
  /* #70: @4 = (@4/@10) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) /= w10;
  /* #71: @0 = [0, 0, 9.8] */
  casadi_copy(casadi_c1, 3, w0);
  /* #72: @4 = (@4-@0) */
  for (i=0, rr=w4, cs=w0; i<3; ++i) (*rr++) -= (*cs++);
  /* #73: output[0][1] = @4 */
  if (res[0]) casadi_copy(w4, 3, res[0]+3);
  /* #74: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #75: @4 = @2[1:4] */
  for (rr=w4, ss=w2+1; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #76: @0 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w0);
  /* #77: @13 = dot(@4, @0) */
  w13 = casadi_dot(3, w4, w0);
  /* #78: @13 = (-@13) */
  w13 = (- w13 );
  /* #79: @1 = @2[0] */
  for (rr=(&w1), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #80: @4 = (@1*@0) */
  for (i=0, rr=w4, cs=w0; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #81: @1 = @2[2] */
  for (rr=(&w1), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #82: @11 = @0[2] */
  for (rr=(&w11), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #83: @3 = (@1*@11) */
  w3  = (w1*w11);
  /* #84: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #85: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #86: @9 = (@12*@6) */
  w9  = (w12*w6);
  /* #87: @3 = (@3-@9) */
  w3 -= w9;
  /* #88: @9 = @0[0] */
  for (rr=(&w9), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #89: @12 = (@12*@9) */
  w12 *= w9;
  /* #90: @8 = @2[1] */
  for (rr=(&w8), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #91: @11 = (@8*@11) */
  w11  = (w8*w11);
  /* #92: @12 = (@12-@11) */
  w12 -= w11;
  /* #93: @8 = (@8*@6) */
  w8 *= w6;
  /* #94: @1 = (@1*@9) */
  w1 *= w9;
  /* #95: @8 = (@8-@1) */
  w8 -= w1;
  /* #96: @0 = vertcat(@3, @12, @8) */
  rr=w0;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w8;
  /* #97: @4 = (@4+@0) */
  for (i=0, rr=w4, cs=w0; i<3; ++i) (*rr++) += (*cs++);
  /* #98: @2 = vertcat(@13, @4) */
  rr=w2;
  *rr++ = w13;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #99: @2 = (@10*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #100: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 4, res[0]+6);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 32;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
